### ISSUE TITLE
Arabic doesn't display correctly with xwindow module

### ISSUE THREAD

**Issue by nabeel910** [polybar/polybar#2111] opened 2020-05-26 16:46 UTC
## Describe the issue
*A clear and concise description of what the bug is.*
Arabic characters don't display correctly with xwindow module even though I'm using a compatible font. I added the font as font 3 and even tried to set the font for the module specifically 
**Expected behavior:**
The characters should interlace? I guess. I'll attach a screenshot as it will explain better.
*A clear and concise description of what you expected to happen.*

**Was it working before?**
No it wasn't working before. At least Not since I started using it.
* Did you also experience this bug in an earlier version of polybar? 
N/A
* If no, what was the last version where this worked correctly? 
N/A

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
nothing special just a bunch of enp2s0. 
Bars launched...
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
warn: module/eth: Failed to query interface 'enp2s0'
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*
This is what it looks like right now : 
![1590510355_May26_18:25:55](https://user-images.githubusercontent.com/60403183/82927335-d9fba780-9f80-11ea-85b2-3e9521192e8c.png)

This is how it should look like : 
![1590510380_May26_18:26:20](https://user-images.githubusercontent.com/60403183/82927404-f7c90c80-9f80-11ea-9959-3b8f5bda1805.png)

## Environment:
* WM: i3
* Distro: Arch Linux
* Output of `polybar -vvv`:
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
## Additional context
*Add any other context that you think is necessary about the problem here.*
I tried using multiple arabic fonts all of which work in the browser but don't work in xwindow module in polybar. e.g Ubuntu Arabic from aur and ttf-arabeyes-fonts

**Comment by patrick96** [comment] 2020-05-26 18:26
Duplicate of #2062 

Polybar can't properly render RTL text.

**Closed by patrick96** 2020-05-26 18:26 UTC

**Comment by nabeel910** [comment] 2020-05-26 18:50
Sorry about that. I searched for Arabic thinking it was a language specific issue.
