### ISSUE TITLE
Polybar can't handle cyclical references

### ISSUE THREAD

**Issue by DRKblade** [polybar/polybar#2227] opened 2020-10-24 13:34 UTC
Using this minimal configuration
```
[bar/main]
scroll-up = ${self.scroll-down}
scroll-down = ${self.scroll-up}
```
One can cause polybar to produce a segmentation fault without displaying the cause of the error.
```
notice: Parsing config file: ./config
warn: No monitor specified, using "eDP-1-1"
Segmentation fault (core dumped)
```
I believe that it is more desirable to handle this situation properly and let the user know the cause of the crash.
Here is the log of the core dump `coredumpctl info`.
```
           PID: 867621 (polybar)
           UID: 1000 (quan)
           GID: 1000 (quan)
        Signal: 11 (SEGV)
     Timestamp: Sat 2020-10-24 20:22:51 +07 (8min ago)
  Command Line: polybar main
    Executable: /usr/local/bin/polybar
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (quan)
       Boot ID: a2e6b69c4abf4355a8decfb5d46dca29
    Machine ID: c3fb10fedd264eac8029b56b610d26ff
      Hostname: quanlaptop
       Storage: /var/lib/systemd/coredump/core.polybar.1000.a2e6b69c4abf4355a8decfb5d46dca29.867621.1603545771000000.zst
       Message: Process 867621 (polybar) of user 1000 dumped core.
                
                Stack trace of thread 867621:
                #0  0x000055725efcdbfa _ZNK7polybar6config11dereferenceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_SA_RKS8_ (polybar + 0x107bfa)
                #1  0x000055725efceaa3 _ZNK7polybar6config3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_ (polybar + 0x108aa3)
                #2  0x000055725efcce1f _ZNK7polybar6config17dereference_localINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_S7_RKS7_SA_ (polybar + 0x106e1f)
                #3  0x000055725efce29c _ZNK7polybar6config11dereferenceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_SA_RKS8_ (polybar + 0x10829c)
                #4  0x000055725efceaa3 _ZNK7polybar6config3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_ (polybar + 0x108aa3)
                #5  0x000055725efcce1f _ZNK7polybar6config17dereference_localINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_S7_RKS7_SA_ (polybar + 0x106e1f)
                #6  0x000055725efce29c _ZNK7polybar6config11dereferenceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_SA_RKS8_ (polybar + 0x10829c)
                #7  0x000055725efceaa3 _ZNK7polybar6config3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_ (polybar + 0x108aa3)
                #8  0x000055725efcce1f _ZNK7polybar6config17dereference_localINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_S7_RKS7_SA_ (polybar + 0x106e1f)
                #9  0x000055725efce29c _ZNK7polybar6config11dereferenceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_SA_RKS8_ (polybar + 0x10829c)
                #10 0x000055725efceaa3 _ZNK7polybar6config3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_ (polybar + 0x108aa3)
                #11 0x000055725efcce1f _ZNK7polybar6config17dereference_localINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_S7_RKS7_SA_ (polybar + 0x106e1f)
                #12 0x000055725efce29c _ZNK7polybar6config11dereferenceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_SA_RKS8_ (polybar + 0x10829c)
                #13 0x000055725efceaa3 _ZNK7polybar6config3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_ (polybar + 0x108aa3)
                #14 0x000055725efcce1f _ZNK7polybar6config17dereference_localINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_S7_RKS7_SA_ (polybar + 0x106e1f)
                #15 0x000055725efce29c _ZNK7polybar6config11dereferenceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_SA_RKS8_ (polybar + 0x10829c)
                #16 0x000055725efceaa3 _ZNK7polybar6config3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_ (polybar + 0x108aa3)
                #17 0x000055725efcce1f _ZNK7polybar6config17dereference_localINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_S7_RKS7_SA_ (polybar + 0x106e1f)
                #18 0x000055725efce29c _ZNK7polybar6config11dereferenceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_SA_RKS8_ (polybar + 0x10829c)
                #19 0x000055725efceaa3 _ZNK7polybar6config3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_ (polybar + 0x108aa3)
                #20 0x000055725efcce1f _ZNK7polybar6config17dereference_localINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_S7_RKS7_SA_ (polybar + 0x106e1f)
                #21 0x000055725efce29c _ZNK7polybar6config11dereferenceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_SA_RKS8_ (polybar + 0x10829c)
                #22 0x000055725efceaa3 _ZNK7polybar6config3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_ (polybar + 0x108aa3)
                #23 0x000055725efcce1f _ZNK7polybar6config17dereference_localINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_S7_RKS7_SA_ (polybar + 0x106e1f)
                #24 0x000055725efce29c _ZNK7polybar6config11dereferenceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_SA_RKS8_ (polybar + 0x10829c)
                #25 0x000055725efceaa3 _ZNK7polybar6config3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_RKS7_SA_ (polybar + 0x108aa3)
                #26 0x000055725efcce1f _ZNK7polybar6config17dereference_localINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_S7_RKS7_SA_ (polybar + 0x106e1f)
                #27 0x000055725efce29c _ZNK7polybar6config11dereferenceINSt7__cxx1112basic_stringIcSt11char_traitsIc
```
This is not tested on the official version of polybar though, but I believe the bug is present there as well.

**Comment by patrick96** [comment] 2020-10-26 10:13
Duplicate of #783

We are already aware of this issue. This happens because we just recursively resolve variable references when a value is requested.
My idea to solve this was to create a dependency graph when we load the config and then we could just check this graph for cycles (similar to what I described for the `inherit` keyword: https://github.com/polybar/polybar/issues/412#issuecomment-376702328). I just never got around to it, because the issue isn't too severe.

**Closed by patrick96** 2020-10-26 10:13 UTC
