### ISSUE TITLE
Polybar shows on wrong monitor after hide

### ISSUE THREAD

**Issue by chrjen** [polybar/polybar#1484] opened 2018-10-23 21:46 UTC
## Describe the issue
When the polybar hides and then shows again it appears on the wrong monitor. 

**Expected behavior:**

The hidden polybars should be appearing on the same monitor on which they were hidden.

**Actual behavior:**

Running `polybar-msg cmd toggle` twice makes all the polybars from all my monitors  show up on a single monitor.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
# File: ~/.config/polybar/config
[bar/middle]
monitor = ${env:MONITOR_MIDDLE}

[bar/right]
inherit = bar/middle
monitor = ${env:MONITOR_RIGHT}
```

```bash
# File: ~/.profile
# Monitors
export MONITOR_MIDDLE=DP-2
export MONITOR_RIGHT=DVI-D-0
```

## Screenshots
![polybars-screenshot](https://i.imgur.com/nHZC75F.png)

## Environment:
* WM: i3-gaps
```
polybar 3.2.1

Features: +alsa +curl +i3 +mpd +network +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/sbin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment] 2018-10-24 06:37
Try to set `override-redirect = true` in the bar section and see if that helps, i3 really likes to mess with bar positioning. I know this will introduce other problems (no space reserved for bars), I just want to confirm that this happens because of i3.

Please also post the output of the bar that is moved when it is toggled (preferably with the additional `-l trace` command line argument).

I will also try to reproduce this on my end.

**Comment by chrjen** [comment] 2018-10-24 07:04
Setting `override-redirect` to true did in fact keep the two polybars on their respective monitors.

As for running polybar with `-l trace` I got this. Output was the same for both bars.

```
* Receiving ipc message
* Hiding bar window
* Receiving ipc message
* Showing bar window
- bar: Force update
* Redrawing bar window
- renderer: flush(1 geom=57x27+0+0, falloff=0)
- bar: Received expose event
```

**Comment by patrick96** [comment] 2018-10-24 07:10
Alright, so it is in fact i3 messing everything up (as usual).

It seems your only option is to leave this option set to `true` and use a transparent dummy bar to make i3 reserve space for your bars as described [here](https://github.com/jaagr/polybar/wiki/Known-Issues#override-redirect-in-i3). Then, if you hide the bars, you will have to kill the dummy bars and restart them once you show the bars again. This way i3 can reclaim the space when you hide the bars.

**Comment by chrjen** [comment] 2018-10-24 07:36
Well that sure is a bodge if there ever was one. Thanks for the answer, I will keep it in mind. Hopefully there will be a native solution with i3 at some point.

**Comment by patrick96** [comment] 2018-12-15 12:49
No, `polybar-msg cmd restart` should not break anything

**Comment by Airblader** [comment] 2019-10-13 07:51
I can't say I appreciate @patrick96's tone, but in trying to hunt this down I would appreciate if someone could tell us what it is polybar does that is supposed to let the window manager know onto which output to place the bar.

From the log file provided by @jluttine in https://github.com/i3/i3/issues/3819 it appears that polybar sets the geometry to x=0/y=0 for both windows, so I guess the geometry when mapping the window is not what polybar tries to use(?)

**Comment by patrick96** [comment] 2019-10-13 15:39
@Airblader Now that I read my comment again it does sound demeaning. I'm sorry about that, it certainly was not meant that way.

Polybar sets the x and y coordinates of the window to position it on the screen. It calculates those coordinates from the monitor specified in the config (or the primary monitor). So for example if I had two 1920p monitors side-by-side and polybar on the monitor on the right at the top, it would set its geometry as `1920x50+1920+0` (assuming it is 50px high). As far as I know we don't use the monitor name for anything else when positioning the bars. Does i3 need polybar to explicitly set the monitor name somewhere?

I am currently on my way back from vacation, so I don't have much time to track this down right now but I will try to dig into this and give a more in-depth answer tonight or tomorrow.

Sorry again, I didn't mean to attack anyone. I'm very much a fan of your and the i3 team's work. I hope we can fix this issue together.

**Comment by Airblader** [comment] 2019-10-14 08:04
> Does i3 need polybar to explicitly set the monitor name somewhere?

No, that is fine, and i3 does / should respect that: https://github.com/i3/i3/blob/next/src/manage.c#L246

The log file provided by @jluttine shows this:

```
10/13/2019 10:25:34 AM - manage.c:manage_window:83 - window 0x01200002
10/13/2019 10:25:34 AM - WM_CLASS changed to polybar (instance), Polybar (class)
10/13/2019 10:25:34 AM - WM_NAME changed to "polybar-nide_eDP-1"                                                                                                                     
10/13/2019 10:25:34 AM - Using legacy window title. Note that in order to get Unicode window titles in i3, the application has to set _NET_WM_NAME (UTF-8)
10/13/2019 10:25:34 AM - window.c:window_update_name:67 - _NET_WM_NAME not specified, not changing
10/13/2019 10:25:34 AM - window.c:window_update_leader:148 - CLIENT_LEADER not set on window 0x01200002.
10/13/2019 10:25:34 AM - window.c:window_update_transient_for:173 - TRANSIENT_FOR not set on window 0x01200002.
10/13/2019 10:25:34 AM - window.c:window_update_strut_partial:210 - Reserved pixels changed to: left = 0, right = 0, top = 27, bottom = 0
10/13/2019 10:25:34 AM - window.c:window_update_role:223 - WM_WINDOW_ROLE not set. 
10/13/2019 10:25:34 AM - window.c:window_update_hints:389 - WM_HINTS not set. 
10/13/2019 10:25:34 AM - window.c:window_update_normal_hints:275 - Could not get WM_NORMAL_HINTS
10/13/2019 10:25:34 AM - startup.c:startup_sequence_get:287 - No _NET_STARTUP_ID set on window 0x01200002
10/13/2019 10:25:34 AM - manage.c:manage_window:195 - startup workspace = (null)
10/13/2019 10:25:34 AM - This window is of type dock 
10/13/2019 10:25:34 AM - randr.c:get_output_containing:108 - comparing x=0 y=0 with x=0 and y=0 width 1280 height 720
10/13/2019 10:25:34 AM - manage.c:manage_window:220 - Starting search at output eDP-1
10/13/2019 10:25:34 AM - manage.c:manage_window:226 - Top dock client
10/13/2019 10:25:34 AM - manage.c:manage_window:245 - Initial geometry: (0, 0, 1280, 27)
10/13/2019 10:25:34 AM - Checking window 0x01200002 (class Polybar)
10/13/2019 10:25:34 AM - dock status matches
```

So the position polybar requested is x=0/y=0. @jluttine Can you please clarify the placement of the outputs you used for that test, i.e. how where the two outputs placed and on which output did they open?

**Comment by jluttine** [comment] 2019-10-14 08:10
I made two tests during the same logging session. In the first one, I "mirrored" the same view to two monitors and then everything worked when hiding and showing the polybar. Then, I placed the two monitors horizontally (eDP-1 on left and HDMI-1 on right, IIRC). In that setup, both polybars appeared on eDP-1 after being hidden. Just to make sure: Are these log file parts from the latter, not former, setup?

**Comment by Lomadriel** [comment] 2019-10-14 09:04
@jluttine I think the problem is fixed on this [branch](https://github.com/polybar/polybar/pull/1823)
Could you test?

**Comment by Airblader** [comment] 2019-10-15 10:49
> Are these log file parts from the latter, not former, setup?

In the log files, there are four polybar windows being mapped in total, grouped into two events: one at 10:45:27 and one at 10:45:43. The logs above are from the latter one.

Out of all four requests, there is only one with an initial geometry of x != 0:

```
10/13/2019 10:25:27 AM - manage.c:manage_window:195 - startup workspace = (null)
10/13/2019 10:25:27 AM - This window is of type dock 
10/13/2019 10:25:27 AM - randr.c:get_output_containing:108 - comparing x=1280 y=0 with x=0 and y=0 width 1280 height 720
10/13/2019 10:25:27 AM - randr.c:get_output_containing:108 - comparing x=1280 y=0 with x=1280 and y=0 width 1280 height 720
10/13/2019 10:25:27 AM - manage.c:manage_window:220 - Starting search at output HDMI-1
10/13/2019 10:25:27 AM - manage.c:manage_window:226 - Top dock client
10/13/2019 10:25:27 AM - manage.c:manage_window:245 - Initial geometry: (1280, 0, 1280, 27)
```

But this is from the first of the two events(?) and also it can be seen that that one actually shows at HDMI-1 while all others go to eDP-1, so it sort of sounds like i3 is doing the correct thing.

**Comment by patrick96** [comment] 2019-10-15 11:28
I have unfortunately not been able to get to my multimonitor setup yet and efforts to simulate on on my laptop using `Xephyr` failed. So the only thing I can do for right now is to comment on what polybar is doing.

The bar is certainly positioned correctly when it is launched. But it seems to me as soon as the bar is unmapped (hidden) and remapped (shown) `xcb_get_geometry` suddenly returns x=0/y=0 in [`manage.c:manage_window:96`](https://github.com/i3/i3/blob/4.17.1/src/manage.c#L96).

Is the window position reset when a window is unmapped? Because polybar only calls `xcb_configure_window_checked` when it is started but not when it is remapped. Maybe this is the issue. I can give a more definitive answer on this once I am at my dual monitor setup.

**Comment by patrick96** [comment] 2019-10-15 13:08
It seems this also happens on a single monitor (it is just not noticeable visually).

I have a bottom bar with the following config:
```dosini
[bar/example]
width = 80%
modules-left = text
background = #ff0000
offset-x = 10%

enable-ipc = true

tray-position = none

bottom = true

[module/text]
type = custom/text
content = Filler

; vim:set ft=dosini:
```

I'm running this in a Xephyr session: `Xephyr +extension RANDR -screen 2560x1440 :1`, the output is called `default`. Here is an excerpt of the i3 log when starting that bar and running `polybar-msg cmd hide` and `polybar-msg cmd show` (full log is attached below):

```
[...] POLYBAR START
[...]
10/15/2019 02:36:02 PM - handlers.c:handle_map_request:262 - window = 0x00800001, serial is 1619.
10/15/2019 02:36:02 PM - manage.c:manage_window:83 - window 0x00800001
10/15/2019 02:36:02 PM - window.c:window_update_name:67 - _NET_WM_NAME not specified, not changing
10/15/2019 02:36:02 PM - window.c:window_update_leader:148 - CLIENT_LEADER not set on window 0x00800001.
10/15/2019 02:36:02 PM - window.c:window_update_transient_for:173 - TRANSIENT_FOR not set on window 0x00800001.
10/15/2019 02:36:02 PM - window.c:window_update_strut_partial:209 - Reserved pixels changed to: left = 0, right = 0, top = 0, bottom = 24
10/15/2019 02:36:02 PM - window.c:window_update_role:223 - WM_WINDOW_ROLE not set.
10/15/2019 02:36:02 PM - window.c:window_update_hints:389 - WM_HINTS not set.
10/15/2019 02:36:02 PM - window.c:window_update_normal_hints:275 - Could not get WM_NORMAL_HINTS
10/15/2019 02:36:02 PM - startup.c:startup_sequence_get:287 - No _NET_STARTUP_ID set on window 0x00800001
10/15/2019 02:36:02 PM - manage.c:manage_window:195 - startup workspace = (null)
10/15/2019 02:36:02 PM - randr.c:get_output_containing:107 - comparing x=256 y=1416 with x=0 and y=0 width 2560 height 1440
10/15/2019 02:36:02 PM - manage.c:manage_window:220 - Starting search at output default
10/15/2019 02:36:02 PM - manage.c:manage_window:229 - Bottom dock client
10/15/2019 02:36:02 PM - manage.c:manage_window:245 - Initial geometry: (256, 1416, 2048, 24)
[...] Presumably the configure request in bar.cpp:814
10/15/2019 02:36:02 PM - handlers.c:handle_configure_request:279 - window 0x00800001 wants to be at 256x1416 with 2048x24
10/15/2019 02:36:02 PM - handlers.c:handle_configure_request:312 - Configure request!
10/15/2019 02:36:02 PM - handlers.c:handle_configure_request:362 - Reconfiguring dock window (con = 0x55faa23df550).
10/15/2019 02:36:02 PM - randr.c:get_output_containing:107 - comparing x=256 y=1416 with x=0 and y=0 width 2560 height 1440
10/15/2019 02:36:02 PM - handlers.c:handle_configure_request:386 - Dock client will not be moved, we only support moving it to another output.
10/15/2019 02:36:02 PM - xcb.c:fake_absolute_configure_notify:85 - fake rect = (0, 1416, 2560, 24)
[...] HIDE
10/15/2019 02:36:18 PM - handlers.c:handle_event:1357 - event type 18, xkb_base 85
10/15/2019 02:36:18 PM - handlers.c:handle_unmap_notify_event:464 - UnmapNotify for 0x00800001 (received from 0x00800001), serial 1691
10/15/2019 02:36:18 PM - tree.c:tree_close_internal:201 - closing 0x55faa23df550, kill_window = 0
[...] SHOW
10/15/2019 02:36:32 PM - handlers.c:handle_event:1357 - event type 20, xkb_base 85
10/15/2019 02:36:32 PM - handlers.c:handle_map_request:262 - window = 0x00800001, serial is 1732.
10/15/2019 02:36:32 PM - manage.c:manage_window:83 - window 0x00800001
10/15/2019 02:36:32 PM - window.c:window_update_name:67 - _NET_WM_NAME not specified, not changing
10/15/2019 02:36:32 PM - window.c:window_update_leader:148 - CLIENT_LEADER not set on window 0x00800001.
10/15/2019 02:36:32 PM - window.c:window_update_transient_for:173 - TRANSIENT_FOR not set on window 0x00800001.
10/15/2019 02:36:32 PM - window.c:window_update_strut_partial:209 - Reserved pixels changed to: left = 0, right = 0, top = 0, bottom = 24
10/15/2019 02:36:32 PM - window.c:window_update_role:223 - WM_WINDOW_ROLE not set.
10/15/2019 02:36:32 PM - window.c:window_update_hints:389 - WM_HINTS not set.
10/15/2019 02:36:32 PM - window.c:window_update_normal_hints:275 - Could not get WM_NORMAL_HINTS
10/15/2019 02:36:32 PM - startup.c:startup_sequence_get:287 - No _NET_STARTUP_ID set on window 0x00800001
10/15/2019 02:36:32 PM - manage.c:manage_window:195 - startup workspace = (null)
10/15/2019 02:36:32 PM - randr.c:get_output_containing:107 - comparing x=0 y=0 with x=0 and y=0 width 2560 height 1440
10/15/2019 02:36:32 PM - manage.c:manage_window:220 - Starting search at output default
10/15/2019 02:36:32 PM - manage.c:manage_window:229 - Bottom dock client
10/15/2019 02:36:32 PM - manage.c:manage_window:245 - Initial geometry: (0, 0, 2560, 24)
[...]
```
[i3log.txt](https://github.com/polybar/polybar/files/3729281/i3log.txt)

The bar requests geometry `2048x24+256+1416` which is also reflected in these two lines:

```
10/15/2019 02:36:02 PM - manage.c:manage_window:245 - Initial geometry: (256, 1416, 2048, 24)
10/15/2019 02:36:02 PM - handlers.c:handle_configure_request:279 - window 0x00800001 wants to be at 256x1416 with 2048x24
```

But after running hide and show, the initial geometry turns into:

```
10/15/2019 02:36:32 PM - manage.c:manage_window:245 - Initial geometry: (0, 0, 2560, 24)
```

I am suspecting this has to do with i3 reparenting the window into its own container. Looking at the output of ` xwininfo -tree -root`, it gives me:
```
     0x20008f "[i3 con] container around 0x55faa23b01f0": ("i3-frame" "i3-frame")  2560x24+0+1416  +0+1416
        1 child:
        0x800001 "polybar-example_default": ("polybar" "Polybar")  2560x24+0+0  +0+1416
```

This is directly after polybar is started and it doesn't change once polybar is hidden and shown again. See how here the geometry already is `2560x24+0+0`. I'm assuming the reparenting in [`manage.c:manage_window:535`](https://github.com/i3/i3/blob/4.17.1/src/manage.c#L535) is the thing that changes the geometry:
```c
    xcb_void_cookie_t rcookie = xcb_reparent_window_checked(conn, window, nc->frame.id, 0, 0);
```

This makes sense since, relative to the container, the bar should be at position 0,0. It seems to me some information is lost when unmapping the window because the container around polybar is destroyed by i3 and when remapping i3 no longer knows the original position of the bar.

From initial testing I was able to get the same `manage.c:manage_window:245 - Initial geometry` message after hiding and showing polybar again by calling `xcb_configure_window_checked` directly before remapping the bar so that i3 has the correct position information again.

I'm not completely sure that this is what's causing the issue on a multi-monitor system because I only have limited testing capabilities right now. Will be able to confirm later and try out my polybar fix on a dual-monitor system.

**Comment by Airblader** [comment] 2019-10-15 20:22
That could be. I tried to scan the ICCCM but couldn't find anything regarding how window managers should behave or what clients can / have to expect apart from the usual rule that a client must be prepared that a window manager can choose to do what it wants (not helpful here).

I tend to believe that a client who unmapped itself and then wants to map again should make sure all appropriate things, including geometry, are set right before mapping, but nonetheless it would be interesting to know if window managers like awesome etc reparent the window to some specific location on the root window. If so I would see no harm in doing the same for i3.

**Comment by Airblader** [comment] 2019-10-15 20:25
I just checked awesome and openbox. awesome seems to in fact reparent to the current location while openbox does so for normal clients but also uses (0, 0) for dock clients (can someone check if this bug occurs in openbox, too?)

In any case, perhaps we should just consider changing this in i3.

**Comment by Airblader** [comment] 2019-10-15 20:35
I've quickly opened https://github.com/i3/i3/pull/3834.

@jluttine or anyone else, could you maybe try running this patch to see if it fixes the issue?

**Comment by patrick96** [comment] 2019-10-15 22:12
I was able to now finally reproduce this problem in i3. I have a polybar fix for which I will open a PR shortly. 

However, that fix only works if polybar unmaps and remaps itself. If polybar is unmapped and remapped with `xdotool windowunmap` and `xdotool windowmap`. it will always move to the monitor on the left.
But when unmapping with an external tool then other bars like `tint2` and `i3bar` both also get placed on the wrong monitor, so I think it's on i3 to handle this. 
Interestingly, `stalonetray` always stays in the right position, I haven't been able to figure out how it does it.

Openbox's behavior is very weird. For one it does not recognize polybar as a dock window. It only recognizes windows as docks if they set `initial_state = WithdrawnState` in `WM_HINTS` or if the second string in `WM_CLASS` is `DockApp`. So it treats it as a normal client and the bug doesn't occur. However, for some reason when remapping it sets the `y` coordinates of the frame to `160` which places polybar in the middle of the screen, not sure what is up with that but it's probably not related to the issue here.

I will try out your PR ASAP.

**Comment by patrick96** [comment] 2019-10-15 22:47
Your PR works for this issue. I have nonetheless added a fix within polybar since there are likely other WMs that do a similar thing.

**Comment by Airblader** [comment] 2019-10-16 06:21
BTW, i3bar also reconfigures itself before unhiding:

https://github.com/i3/i3/blob/next/i3bar/src/xcb.c#L356

**Comment by Airblader** [comment] 2019-10-16 09:57
The fix in i3 is merged now. Thanks everyone :-)

**Comment by patrick96** [comment] 2019-10-16 16:02
> BTW, i3bar also reconfigures itself before unhiding:

I see, didn't know i3bar could hide itself. That's why I only tested with `xdotool`.

> The fix in i3 is merged now.

Awesome!

I have now adapted my PR to also reconfigure width, height, stacking order, struts and hints just to be on the safe side. It should be merged shortly.

**Closed** 2019-10-21 11:22 UTC
