### ISSUE TITLE
 The problem is that using {} in the polybar is crashing it, I don't know why. Does anyone have any solution??? 

### ISSUE THREAD

**Issue by edufariasud** [polybar/polybar#2529] opened 2021-10-09 00:49 UTC
My friends, help here.

 I need to use this code in my polybar for a project.

 bspc desktop -f '^{1-9,10}' 

The problem is that using {} in the polybar is crashing it, I don't know why. Does anyone have any solution??? 

Either modifying the polybar so it doesn't crash or writing this function differently.

This specific code is a command for bspwm to switch between desktops. Usually this code is executed via a key combination, but for this project I need to assign this code to a button on the polybar. Thanks, guys!!! :)

**Comment by patrick96** [comment] 2021-10-09 12:12
Duplicate of #2040

I already answered this on gitter.

**Closed by patrick96** 2021-10-09 12:12 UTC
