### ISSUE TITLE
Radius with tray not working

### ISSUE THREAD

**Issue by cpiber** [polybar/polybar#2201] opened 2020-10-10 07:51 UTC
## Describe the issue
A tray on left or right disables radius on that side. Setting the tray background to transparent reveals the background (with a straight edge to the rest the bar)

**Expected behavior:**

Radius around tray

**Actual behavior:**

No radius, but same background

**Was it working before?**

First time using polybar

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/test]
width = 100%
height = 27
background = #fff
radius = 6.0
;need at least one module
modules-center = date
tray-position = right

[module/date]
type = internal/date
time = %H:%M
;need to set label, otherwise radius doesn't work
label = %time%
```

## Polybar Log
Nothing

## Screenshots

tray: ![image](https://user-images.githubusercontent.com/59023762/95649455-bd9a7a80-0add-11eb-9652-da11ae007921.png)

other side: ![image](https://user-images.githubusercontent.com/59023762/95649510-fe928f00-0add-11eb-8fa8-dbd039113948.png)

## Environment:
* WM: i3
* Distro: Ubuntu 20.04
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: None
Compiler: /usr/bin/c++
Compiler flags: -g -O2 -fdebug-prefix-map=/build/polybar-IKpyNi/polybar-3.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wpedantic 
Linker flags: -Wl,-Bsymbolic-functions -Wl,-z,relro
```

**Comment by patrick96** [comment] 2020-10-10 14:43
Duplicate of #651

**Closed by patrick96** 2020-10-10 14:43 UTC
