### ISSUE TITLE
xworkspaces getting out of sync in 3.5.0

### ISSUE THREAD

**Issue by vaygr** [polybar/polybar#2272] opened 2020-12-05 19:07 UTC
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

After bumping polybar to 3.5.0 (I actually tested this 2 weeks ago with just #882 integrated – same problem, so I believe this PR is the culprit) after a few switches between workspaces, polybar displays as active not the one you're actually on.

**Expected behavior:**

polybar highlights correct workspace as active.

**Actual behavior:**

After a few switches polybar highlights the previous workspace as active.

**Was it working before?**

Yes.

* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?

No

* If no, what was the last version where this worked correctly?

**3.4.3**

## To Reproduce

The following is a partial config of 2 bars (`top` & `bottom`). To better understand what happens, there's a screenshot attached with 3 active bars:

1. top bar running **3.4.3**
2. bottom bar running **3.4.3**
3. top bar running **3.5.0** on top of bar №1

```dosini
…

[bar/top]
width = 100%
height = 25
fixed-center = true
…
ws-icon-0 = "▰ ▱ ▱;    Base   "
ws-icon-1 = " ▱ ▰ ▱ ;     Lab    "
ws-icon-2 = " ▱ ▱ ▰ ;   Factory  "

active-background = #3f3f3f
active-underline = #3f3f3f

[bar/bottom]
width = 100%
height = 25
offset-y = 25
fixed-center = true
…
ws-icon-0 = "▰ ▱ ▱;             "
ws-icon-1 = " ▱ ▰ ▱ ;              "
ws-icon-2 = " ▱ ▱ ▰ ;              "

active-background = #3f3f3f
active-underline = #ffffff
…

[module/ewmh]
type = internal/xworkspaces

pin-workspaces = true

enable-click = true

enable-scroll = false

icon-0 = ${root.ws-icon-0}
icon-1 = ${root.ws-icon-1}
icon-2 = ${root.ws-icon-2}
icon-default = 

format = <label-state>

label-monitor = %name%

label-active = %icon%
label-active-foreground = #ffffff
label-active-background = ${root.active-background}
label-active-underline = ${root.active-underline}

label-occupied = %icon%

label-urgent = %icon%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40

label-empty = %icon%
label-empty-foreground = #55
```

To reproduce you have to click between workspaces 1 → 2 → 3 → 2 → 1 and so on, and on the 3rd or 4th iteration after you click on the next workspace polybar highlighting doesn't change.

On the other hand, if I click on the bottom bar running 3.4.3 that doesn't happen no matter how many times I switch between workspaces.

## Polybar Log

```
notice: Parsing config file: /home/user/.config/polybar/config
```

## Screenshots

![shot-2020-12-05_103531](https://user-images.githubusercontent.com/8810597/101260815-523ce580-36e7-11eb-8ff6-b75818f43ed3.png)

## Environment:
* WM: Fluxbox 1.3.7
* Distro: Source Mage stable
* Output of `polybar -vvv`:

```
polybar 3.5.0

Features: +alsa +curl -i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/clang++
Compiler flags: -Wno-error=unused-command-line-argument -march=corei7-avx -fPIC -DPIC -pipe -Os -Wall -Wextra -Wpedantic -Wno-error=parentheses-equality -Wno-zero-length-array -stdlib=libc++ -Wno-error=unused-command-line-argument -march=corei7-avx -fPIC -DPIC -pipe -Os
Linker flags: -s -lc++ -lc++abi
```

**Comment by patrick96** [comment] 2020-12-05 19:11
Thanks for the report.

Could you please also post the output of `xprop -root` when you are in this inconsistent state?

**Comment by vaygr** [comment] 2020-12-05 19:15
```shell
$ xprop -root
_NET_WM_USER_TIME(CARDINAL) = 194699912
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x2c00076
AT_SPI_BUS(STRING) = "unix:abstract=/tmp/dbus-DRZZsssWJu,guid=63e6dcc39735009b56ed579f5fbb2b08"
PULSE_COOKIE(STRING) = "36f374e445864f9dd2d8959ffd13174b07559528dd3d4f1ff40e7c70742df5a7977b97c4d9982ff94385a5808630643b317dc1bc7fdce656d8396b797607a7d823c9cecedd367fdbed30994a10835a18fdc23cdf532d112c7c5fa3f7eab800f653120bfdcfe8b541b3eaf7859ecbd5bd41fc127442a76ca8b35f45e2be3902873fcf879026c04dd0f825110fd1a5c3dce0414caabdb0dca986fab773bef832ed9ef7b42a02c69b3fd8abbbb41c387376739089c16d598b0e3c5a933a1932737d3fa068b71e38513f73513178d3cd9acdafac52934bd6ff0b2f72bf65daecc132bf98e2c6941b07b95a5b8be07f178a947d9b6beba17ba9b0ea1277fd5ae89407"
PULSE_SERVER(STRING) = "{38914705784ce71ebd639cee0000137e}unix:/tmp/pulse-PKdhtXMmr18n/native"
PULSE_ID(STRING) = "8000@38914705784ce71ebd639cee0000137e/1510"
_NET_WORKAREA(CARDINAL) = 0, 55, 1920, 1002, 0, 55, 1920, 1002, 0, 55, 1920, 1002
_NET_DESKTOP_GEOMETRY(CARDINAL) = 1920, 1080
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x2600004, 0x840000b, 0x3a00002, 0x3800003, 0x5c00005, 0x800000b, 0x8600003, 0x2c00076
_NET_CLIENT_LIST(WINDOW): window id # 0x2600004, 0x840000b, 0x3a00002, 0x3800003, 0x5c00005, 0x800000b, 0x8600003, 0x2c00076
_NET_DESKTOP_NAMES(UTF8_STRING) = "▰ ▱ ▱", " ▱ ▰ ▱ ", " ▱ ▱ ▰ "
_NET_CURRENT_DESKTOP(CARDINAL) = 0
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 3
_NET_SUPPORTED(ATOM) = _NET_WM_STRUT, _NET_WM_STATE, _NET_WM_NAME, _NET_WM_ICON, _NET_WM_ICON_NAME, _NET_WM_STATE_STICKY, _NET_WM_STATE_SHADED, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_MODAL, _NET_WM_STATE_BELOW, _NET_WM_STATE_ABOVE, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_ALLOWED_ACTIONS, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_STICK, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_NUMBER_OF_DESKTOPS, _NET_CURRENT_DESKTOP, _NET_ACTIVE_WINDOW, _NET_CLOSE_WINDOW, _NET_MOVERESIZE_WINDOW, _NET_WORKAREA, _NET_RESTACK_WINDOW, _NET_REQUEST_FRAME_EXTENTS, _NET_WM_MOVERESIZE, _NET_FRAME_EXTENTS, _NET_WM_DESKTOP, _NET_DESKTOP_NAMES, _NET_DESKTOP_VIEWPORT, _NET_DESKTOP_GEOMETRY, _NET_SUPPORTING_WM_CHECK
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x2e000c0
_BLACKBOX_PID(CARDINAL) = 1497
XAUTOLOCK_SEMAPHORE_PID(INTEGER) = 37, 101, 0, 0
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0x1c00003
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x1c00003
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 7
XFree86_DDC_EDID1_RAWDATA(INTEGER) = 0, -1, -1, -1, -1, -1, -1, 0, 9, -27, -33, 6, 0, 0, 0, 0, 1, 26, 1, 4, -91, 31, 17, 120, 2, -122, 49, -93, 84, 78, -101, 37, 14, 80, 84, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 60, 55, -128, -34, 112, 56, 20, 64, 60, 32, 54, 0, 53, -83, 16, 0, 0, 26, 48, 44, -128, -34, 112, 56, 20, 64, 48, 32, 54, 0, 53, -83, 16, 0, 0, 26, 0, 0, 0, -2, 0, 66, 79, 69, 32, 67, 81, 10, 32, 32, 32, 32, 32, 32, 0, 0, 0, -2, 0, 72, 86, 49, 52, 48, 70, 72, 77, 45, 78, 54, 49, 10, 0, 73
```

**Comment by patrick96** [comment] 2020-12-05 22:16
I was only able to reproduce this on fluxbox, but not on hlwm.

I can also confirm that #882 caused this issue.
What seemed like the cause is that if that two events from the WM are too close together (< 25ms), the second event won't trigger an update. In this case, the second event was the one that actually set the active workspace and so the bar wasn't updated (but the module state was actually completely correct).
I have now removed that restriction, and when every event triggers an update, this seems to work fine.

I don't know why exactly that PR broke this because that 25ms restriction was there for a long time before that PR. My best guess is that the additional mutexes introduced in that PR somehow affected the timing of these events.

**Comment by patrick96** [comment] 2020-12-05 22:29
Fixed in #2275

**Closed by patrick96** 2020-12-05 22:29 UTC

**Comment by floppyman** [comment] 2022-03-03 08:22
Hi

Sorry for opening an old issue, however i am experience matching symptoms in the latest git version on HLWM.

It seems a bit random, and you can switch between them normally for a bit but then it skips highlighting a workspace.

More often it seems to be empty workspaces that triggers it.

I have confirmed with `xprop -root -spy` that swithing through workspaces does infact change the workspace when it happens

`polybar -vvv`
```
polybar -vvv
polybar 3.6.0-2-g219171cf

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

`polybar xworkspaces`
```
[module/ewmh]
type = internal/xworkspaces

pin-workspaces = false
enable-click = true
enable-scroll = false
reverse-scroll = false
format-padding = 0
format = <label-state>
format-foreground = ${colors.cyan}
format-background = ${colors.background_trans}

label-monitor = %name%

label-active-foreground = ${colors.cyan}
label-active-background = ${colors.background_trans}
label-active-padding = 1
label-active-font = 2

label-occupied-foreground = ${colors.cyan50}
label-occupied-background = ${colors.background_trans}
label-occupied-padding = 1
label-occupied-font = 2

label-urgent-foreground = ${colors.pink}
label-urgent-background = ${colors.background_trans}
label-urgent-underline =
label-urgent-padding = 1
label-urgent-font = 2

label-empty-foreground = ${colors.foreground50}
label-empty-background = ${colors.background_trans}
label-empty-padding = 1
label-empty-font = 2
```

**Comment by patrick96** [comment] 2022-03-03 20:55
@floppyman Can you create a bug report for this. And also try to apply the following patch to polybar: https://gist.github.com/patrick96/a93b49ae3f31fdfdbca0452c64ee348b

This will print a bunch of debug information about which atoms the xworkspaces module is notified about.

Try to reproduce the bug while also running `xprop -root -spy` and if possible indicate in the output of both polybar and xprop where the bug occurs.
