### ISSUE TITLE
tray icons are floating at the front of applications

### ISSUE THREAD

**Issue by Yves0** [polybar/polybar#1833] opened 2019-07-07 09:40 UTC
## Describe the issue
see screenshot
## Screenshots
![image](https://user-images.githubusercontent.com/17212864/60766606-8a00c180-a0de-11e9-9d6b-237451d3f4a6.png)

## Environment:
* WM: i3-wm
* Distro: archlinux
* Output of `polybar -vvv`:
```
➜  ~ polybar -vvv
polybar 3.3.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -Wno-deprecated-copy -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by Lomadriel** [comment] 2019-07-24 18:42
Duplicate of https://github.com/polybar/polybar/issues/425 but thanks for the report ;)

**Closed by Lomadriel** 2019-07-24 18:42 UTC
Labels: duplicate
