### ISSUE TITLE
Changing volume on internal/pulseaudio might cause crash after restart of pulseaudio

### ISSUE THREAD

**Issue by Joschasa** [polybar/polybar#2112] opened 2020-05-27 09:43 UTC
## Describe the issue
Trying to change the volume in `internal/pulseaudio` after killing pulseaudio, even if pulseaudio restarted again.

**Expected behavior:**
Polybar should not crash.
Maybe showing disconnected state or even better reconnect and change the current volume.

**Actual behavior:**
Polybar crashes.

**Was it working before?**
Not sure this ever worked, had crashing issues for some time.
Was able to check and reproduce this just now.

## To Reproduce
My internal/pulseaudio config:
```dosini
[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume> <bar-volume>
label-volume = %percentage%%
label-volume-foreground = ${root.foreground}

label-muted = muted
label-muted-foreground = #666

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}
```
Running `pulseaudio --kill` and trying to change the volume causes the crash.
Even if pulseaudio was restarted in the meantime.

## Polybar Log
```
polybar|warn:  pulseaudio: using default sink alsa_output.pci-0000_0c_00.4.iec958-stereo
polybar|warn:  Ignoring restack of i3 window (not needed when `override-redirect = false`)
Assertion 'o' failed at ../pulseaudio/src/pulse/operation.c:136, function pa_operation_get_state(). Aborting.
```

## Environment:
* WM: i3wm
* Distro: arch
* Output of `polybar -vvv`:
```polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now```

## Additional context
I guess this stacktrace describes the issue:
```                Stack trace of thread 436362:
                #0  0x00007f93438a32e5 raise (libc.so.6 + 0x3c2e5)
                #1  0x00007f934388c853 abort (libc.so.6 + 0x25853)
                #2  0x00007f9343e64d65 pa_operation_get_state (libpulse.so.0 + 0x1ad65)
                #3  0x0000562eb2fdaf7a _ZN7polybar10pulseaudio10inc_volumeEi (polybar + 0x28af7a)
                #4  0x0000562eb2f5a45c _ZN7polybar7modules17pulseaudio_module5inputEONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (polybar + 0x20a45c)
                #5  0x0000562eb2e96288 _ZN7polybar10controller17process_inputdataEv (polybar + 0x146288)
                #6  0x0000562eb2e9a868 _ZN7polybar10controller18process_eventqueueEv (polybar + 0x14a868)
                #7  0x00007f9343c7eb74 execute_native_thread_routine (libstdc++.so.6 + 0xcfb74)
                #8  0x00007f9343a37422 start_thread (libpthread.so.0 + 0x9422)
                #9  0x00007f9343966b83 __clone (libc.so.6 + 0xffb83)
```

**Comment by patrick96** [comment] 2020-05-27 20:09
Duplicate of #1580 

I ran into some issues when I tried to fix it back then and never came around to resolving those.

**Closed by patrick96** 2020-05-27 20:09 UTC
