### ISSUE TITLE
error while loading libjsoncpp.so

### ISSUE THREAD

**Issue by grravity** [polybar/polybar#2053] opened 2020-04-08 14:28 UTC
## Describe the issue
*Just updated my Arch system, restarted and polybar wasn't starting. I tried manually starting and am getting "`polybar: error while loading shared libraries: libjsoncpp.so.21: cannot open shared object file: no such file or directory.`
I was messing around with the config file, removing stuff so I figured that might've done something (despite no issues before) so I restored the backup I made before screwing with it and tried restarting polybar and still not working. I also tried reinstalling the `libjsoncpp.so` depdency, no errors, reinstalled fine. Polybar still not working and giving the same error.*

## Environment:
* WM: i3gaps
* Distro: 5.6.2-arch1-2
* Output of `polybar -vvv`:  `polybar: error while loading shared libraries: libjsoncpp.so.21: cannot open shared object file: no such file or directory.`

**Comment by Lomadriel** [comment] 2020-04-08 18:51
Duplicate of https://github.com/polybar/polybar/issues/2051

**Closed by Lomadriel** 2020-04-08 18:51 UTC
