### ISSUE TITLE
Making the system tray a module

### ISSUE THREAD

**Issue by tinbolw** [polybar/polybar#2366] opened 2021-01-31 00:15 UTC
## Is your feature request related to a problem? Please describe.

Allowing modules to be further right/left than the system tray is impossible since it's not a module, limiting customization of the system tray's position to just three places.
## Why does polybar need this feature?

I think a lot of users would appreciate the feature of being able to have the system tray as a module that can fit in and be sorted with your other modules.
## Describe the solution you'd like

Adding a module for a system tray. Some config options might be : grid size (3x3,4x4), icon sorting, moving other modules to be within the system tray module. 
## Describe alternatives you've considered

Allowing the system tray to be sorted alongside modules as opposed to making it a module itself is an alternative solution.
## Additional context

Example of the current system tray being forced to the far right and interrupting the style of the bar:
https://i.imgur.com/RhRGhV7.png

**Comment by patrick96** [comment] 2021-01-31 00:50
Duplicate of #314

**Closed by patrick96** 2021-01-31 00:50 UTC
