### ISSUE TITLE
Battery module- different color/formatting when battery is dangerously low?

### ISSUE THREAD

**Issue by btlvr** [polybar/polybar#1956] opened 2019-12-17 03:11 UTC
I see that polybar provides the built-in `battery` module ([documented here](https://github.com/polybar/polybar/wiki/Module:-battery)). 

I would like my battery percentage in the status bar to change color when the battery percentage drops below an arbitrary level, to make sure it grabs my attention. I'm not seeing anything in the documentation that describes how to configure this. Am I missing something, or is polybar missing this feature?

I've been using a custom shell script / module to accomplish this. I'd prefer to do it purely in the polybar config.

**Comment by patrick96** [comment] 2019-12-17 08:01
Duplicate of #415

See the "workaround" at the bottom. Having the ramp leak out the background color into the label works.

**Closed by patrick96** 2019-12-17 08:01 UTC
