### ISSUE TITLE
"module-margin-left = -1" causes total system halt, Arch AUR package for Polybar 3.1

### ISSUE THREAD

**Issue by usrfriendly** [polybar/polybar#1265] opened 2018-06-01 05:57 UTC
I'm just working on my polybar config, experimenting with settings just to see what happens, and I set this setting in the default polybar config:

`module-margin-left = -1`

I'm running Arch, with linux-lts 4.14.44, and xorg-server 1.20.0-2, with Intel hd3000 graphics using the kernel kms intel driver, without compton running (normally I would, but haven't set it up yet).  I'm running a vanilla i3-gaps config (pulled via the i3 group in Arch), and am launching polybar via dmenu running `polybar example`, and starting my session with sddm.  If there's any other info that can help, I'll share.

Just tested, this also happens on git the latest commit/version b70d5b5

**Comment by patrick96** [comment] 2018-06-01 07:54
Negative margins aren't supported I think, but this is concerning.
I will try to reproduce this, in the mean time, does it immediately freeze? Can you switch to another tty? Also can you try to get the output of polybar in the terminal (you may need to redirct it to a file because you may not see it, if the system stops)

From glancing at the code, the margin is loaded as an unsigned number and it's possible that it loads -1 and then converts it to an unsigned number, making the effective number 2^32 - 1

**Comment by a-roc** [comment] 2018-06-01 08:34
It would take five to ten seconds for any input to register, or the system would freeze completely.  It wasn't consistent, but one of these two things happened.

I ran `polybar example &> polydump.txt` to dump the output from my config running with the bad flag, and have attached the file below.  i believe I ran an -l flag, but I don't remember which, sorry.  If there's a recommended one, I'll get the output ASAP.

[polydump.txt](https://github.com/jaagr/polybar/files/2061823/polydump.txt)

**Comment by patrick96** [comment] 2018-06-01 08:37
This seems to be the problem:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

Can you run polybar with `-l trace`, that will help us track down where exactly this happens

**Comment by a-roc** [comment] 2018-06-01 08:47
[polydump.txt](https://github.com/jaagr/polybar/files/2061956/polydump.txt)

This was caught with `polybar example -l trace &> polydump.txt`

**Comment by patrick96** [comment] 2018-06-01 12:02
I was able to reproduce this, but only by also tinkering with the code. What polybar does is store a string that contains `margin-left` many spaces, if `-1` is used and interpreted as `2^32-1` then this many bytes will be allocated and if you run out of memory because of that, this happens. Out of curiosity, how much RAM does your system have? I will try to figure out a way for polybar to not parse negative numbers for such fields

**Comment by patrick96** [comment] 2018-06-01 12:48
Alright, the changes for this will likely conflict with #1237, so I'm going to fix this issue once the PR is merged. I may also fix it inside the PR depending on how much restructuring I have to do in the code anyway.

For now, just don't use negative numbers for margin and padding (or basically anywhere else, I don't even think we allow negative numbers anywhere).

**Comment by a-roc** [comment] 2018-06-01 20:11
I don't plan to use negatives, especially if they aren't supported anyway, I was just poking around a new program, before checking documentation.

I missed the other comment, but I've got 8GB of RAM, if that's at all relevant at this point.

**Comment by patrick96** [comment] 2018-06-02 09:14
Yeah, negative numbers don't really make sense, but it's still a problem when they cause this much trouble. Thanks for reporting!

The machine I tested this on I think had 16GB, so that's probably why I couldn't directly reproduce the crash because 4 extra GB used didn't bog down my machine that much.

**Comment by scrouthtv** [comment] 2019-07-12 20:06
Still a thing on 3.3.0-92-g7724c4dc

**Comment by Lomadriel** [comment] 2019-07-12 20:50
One of my PR fixes this bug but you'll need to wait until the merge.

**Comment by cyclowns** [comment] 2020-01-18 05:12
also happens on manjaro using the Arch AUR package on 3.4.1 when i set 'padding = -1'

**Closed** 2022-02-20 20:08 UTC
Labels: bug, confirmed
