### ISSUE TITLE
[Bug]: xworkspaces sorts workspaces in a chaotic manner

### ISSUE THREAD

**Issue by svalaskevicius** [polybar/polybar#2890] opened 2023-01-05 23:59 UTC
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

two monitor setup, when switching workspaces across they get reshuffled in the bar and jump about - using xmonad.

is there a way to have them listed statically in the order reported by X?

### Minimal config

```dosini
default config using 

[module/workspaces]
type = internal/xworkspaces
```
```


### Polybar log

_No response_

### Expected behavior

statically ordered workspace icons

### Actual behavior

icons get shuffled about

### Window Manager and Version

xmonad 57c3a13

### Linux Distribution

NixOS 22.11

### Polybar version

```text
polybar 3.6.3

Features: +alsa -curl -i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gcc-wrapper-11.3.0/bin/g++
Compiler flags:  -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags:  -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

**Comment by patrick96** [comment] 2023-01-12 21:39
Workspaces are grouped by monitors (per monitor the order should be as reported by your WM).

Looks like a duplicate of #2603

**Closed by patrick96** 2023-01-12 21:39 UTC
Labels: bug, needs confirmation
