### ISSUE TITLE
Error while building doc

### ISSUE THREAD

**Issue by wizardofsource** [polybar/polybar#2191] opened 2020-10-03 07:00 UTC
## Build Process
*Describe how you build polybar, list the exact commands you are using:*
I clone the repository, because I want to build the documentation. 
I read the instructions in ./doc.
I run:
```
cd ./doc
mkdir build
cd build
cmake ..
make
``` 
I get the following error.
```
/bin/sh: 1: b: not found
```
I search where it comes from.
It comes from ./doc/build/CMakeFiles/doc_man.dir/build.make
and also ./doc/build/CMakeFiles/doc_html.dir/build.make
The command that is wrong is on line ~57 and its the rule CMakeFiles/doc_man:
The reason that it's wrong is that there is a newline before the -b flag. 
Thus the shell tries to interpret the part after the -b flag as a separate command.

## Environment:
Ubuntu 20.04
zsh

**Comment by patrick96** [comment] 2020-10-03 13:02
I was able to reproduce this. The problem was that the variable with the sphinx-build executable name was empty. I will merge the fix for this shortly.

For now you can do `cmake -DSPHINX_BUILD=sphinx-build ..` instead of just `cmake ..` to fix this yourself.

**Closed** 2020-10-03 13:37 UTC
Labels: bug, build, confirmed, documentation

**Comment by patrick96** [comment] 2020-10-03 13:38
Good catch. Turns out our CI documentation builds were broken for a long time, but we never noticed because of this.
