### ISSUE TITLE
VPN module doesn't detect 'tun0'

### ISSUE THREAD

**Issue by jeames00** [polybar/polybar#2209] opened 2020-10-14 09:50 UTC
## Describe the issue
VPN module does not detect the tun0 interface.

**Expected behavior:**

After connecting to VPN, I expect the text I've specified in the 'label-connected' field to be displayed in my polybar.

**Actual behavior:**

The text for 'label-disconnected' keeps being displayed instead.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
No
* If no, what was the last version where this worked correctly?
It stopped working today, not after updating Polybar but after switching from 'NetworkManager' to 'wpa_supplicant'.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[module/vpn]
type = internal/network
interface = tun0
interval = 3.0

format-connected = <label-connected>
format-connected-background = ${colors.label}
format-connected-foreground = ${colors.white}
format-connected-prefix = %{T2}%{T-}
format-connected-prefix-background = ${colors.prefix}
format-connected-prefix-foreground = ${colors.white}
format-connected-prefix-padding = 1
label-connected = " VPN CONNECTED "

format-disconnected = <label-disconnected>
format-disconnected-background = ${colors.label}
format-disconnected-foreground = ${colors.red}
format-disconnected-prefix = %{T2}%{T-}
format-disconnected-prefix-background = ${colors.prefix}
format-disconnected-prefix-foreground = ${colors.red}
format-disconnected-prefix-padding = 1
label-disconnected = " VPN DISCONNECTED "
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*
* Perhaps compatibility with 'wpa_supplicant'?
* I connect to VPN with following command:
anyconnect --user=$username --servercert $server_cert --passwd-on-stdin --cafile=cert.crt https://<ip-address>:22

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
/home/username/.config/polybar/polybar-fox/launch.sh: line 4: killall: command not found
warn: The config parameter `module/bspwm.label-active` is deprecated, use `module/bspwm.label-focused and label-dimmed-focused` instead.
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: bspwm
* Distro: Void
* Output of `polybar -vvv`:
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/lib/ccache/bin/g++
Compiler flags: -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2  -Wno-error=deprecated-declarations -g -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
## Additional context
*Add any other context that you think is necessary about the problem here.*

> ip link | grep tun
910: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1434 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 500

**Comment by jeames00** [comment] 2020-10-14 11:38
> Try setting `unknown-as-up = true` because it looks like your interface reports an unknown state: `state UNKNOWN`

Just tried adding `unknown-as-up = true` to the VPN module and restarted polybar but issue persists I'm afraid. Log output hasn't changed.

FWIW, output of `ethtool -i tun0` is:

```
driver: tun
version: 1.6
firmware-version:
expansion-rom-version:
bus-info: tun
supports-statistics: no
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

**Comment by patrick96** [comment] 2020-10-14 18:02
Hmm. I will now go through the steps the network module goes through to check whether an interface is connected:

* Does the file `/sys/class/net/tun0/wireless` exist?
* What are the contents of the `/sys/class/net/tun0/operstate` file?
* What is the output of `ethtool tun0`?

**Comment by jeames00** [comment] 2020-10-15 00:08
`ls /sys/class/net/tun0/wireless`
Specified path '/sys/class/net/tun0/wireless' doesn't exist.

`
cat /sys/class/net/tun0/operstate`
unknown

`sudo ethtool tun0`
Settings for tun0:
	Supported ports: [  ]
	Supported link modes:   Not reported
	Supported pause frame use: No
	Supports auto-negotiation: No
	Supported FEC modes: Not reported
	Advertised link modes:  Not reported
	Advertised pause frame use: No
	Advertised auto-negotiation: No
	Advertised FEC modes: Not reported
	Speed: 10Mb/s
	Duplex: Full
	Auto-negotiation: off
	Port: Twisted Pair
	PHYAD: 0
	Transceiver: internal
	MDI-X: Unknown
        Current message level: 0x00000000 (0)

Link detected: yes

**Comment by patrick96** [comment] 2020-10-15 09:53
I'm having a hard time reproducing this, so I think this is something specific to your setup/machine and not a broader issue with the network module.

There are two things that could go wrong: Either polybar doesn't properly detect that this is a `tun` device or the connection check fails for some reason.

The thing that confuses me is that the outputs of the `ethtool` command that you posted suggest that polybar should properly detect it as a `tun` device and that it is connected, because it checks if the driver starts with `tun` and whether there is a link.

How exactly did you switch away from NetworkManager? Because wpa_supplicant doesn't really have anything to do with managing your network connections and vpn (I think), it is only responsible for your wireless connection and NetworkManager uses it too.

**Comment by jeames00** [comment] 2020-10-15 13:53
I have switched back to NetworkManager and it's working successfully now. The outputs of those three commands you asked for previously remain the same. Puzzling. Must be something deeper down that wpa_supplicant does (or doesn't do). I'm running Void Linux (which means runit rather than systemd) so I ran the following to switch from NetworkManager to wpa_supplicant:

sudo sv stop NetworkManager
sudo rm /var/service/NetworkManager
sudo ln -s /etc/sv/dhcpcd /var/service
sudo ln -s /etc/sv/wpa_supplicant /var/service
sudo sv start dhcpcd
sudo sv start wpa_supplicant

As above, wpa_supplicant requires dhcpcd unlike NetworkManager which I assume has its own dhcp client.

**Comment by patrick96** [comment] 2020-10-17 15:12
Hmm, so there must have been that NetworkManager was doing that allowed polybar to properly detect the interface.

I am closing this since we really have no way to reproduce this, unless you want to dig into this with gdb and figure out where things go wrong. If so, let me know ;)

**Closed by patrick96** 2020-10-17 15:12 UTC
