### ISSUE TITLE
xworkspaces occupied label

### ISSUE THREAD

**Issue by hackedWifi** [polybar/polybar#1917] opened 2019-10-25 22:43 UTC
## Describe the issue
*A clear and concise description of what the bug is.*
When launching a application in a wokspace then quit it. The label occupied background color, foreground color, and icon remain there. Event the wokspace is empty. It still show as occupied.
If I moved to a different workspace and open an application there. The label in the already marked occupied goes back to empty. (lets note that this workspace was empty)
**Expected behavior:**
Workspace should change to any configuration for an empty workspace
*A clear and concise description of what you expected to happen.*
I have a different icon for empty, occupied, and active. So I will expect it to change.
**Actual behavior:**

*What actually happens*

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
I cant test this because this was a commit that was recently added to the repo
* If no, what was the last version where this worked correctly?

## To Reproduce

*A minimal but complete config with which the problem occurs:*
```dosini

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
* Parsing config file: spectrwm.bar
* Enabling xresource manager
* Loaded monitor eDP1 (3840x2160+0+0)
* Found matching X resource "background" (value=#2d2d2d)
* Found matching X resource "foreground" (value=#d3d0c8)
* Bar geometry: 1152x60+38+11; Borders: 0,0,0,0
* Found matching X resource "color6" (value=#66cccc)
* Found matching X resource "background" (value=#2d2d2d)
* Found matching X resource "foreground" (value=#d3d0c8)
* Found matching X resource "background" (value=#2d2d2d)
* Found matching X resource "color14" (value=#d27b53)
* Starting application
* Starting module/spectrwm
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=3)
* Configured DPI = 220x220
* Loaded font "Iosevka:size=10" (name=Iosevka, offset=3, file=/home/archietux/.local/share/fonts/Iosevka Nerd Font Complete.ttf)
* Loaded font "Iosevka:size=13" (name=Iosevka, offset=3, file=/home/archietux/.local/share/fonts/Iosevka Nerd Font Complete.ttf)
* Loaded font "siji:pixelsize=10" (name=siji, offset=3, file=/usr/share/fonts/TTF/siji.ttf)
* Bar window: 0x1a00002
* Disabling tray manager (reason: missing `tray-position`)
* module/spectrwm: Rebuilding cache
* Redrawing bar window
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: spectrwm 
* Distro: Archlinux
* Output of `polybar -vvv`:
polybar 3.4.0-24-g2b31a3f1

Features: +alsa +curl -i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by patrick96** [comment] 2019-11-03 01:29
I'm unable to reproduce this. What version of spectrwm are you using? Could you please also post your `xworkspaces` config.

Just to make sure I have understood right, what happens is:

* You open an application in the current workspace (this itself doesn't change the label since the label is still `label-active`)
* You close this application and now the workspace is empty (the label is still `label-active`)
* You switch to another workspace (the label on the old workspace becomes `label-occupied`)
* You open an application in the new workspace (the label in the old workspace goes to `label-empty`).

Is this correct?

**Comment by patrick96** [comment] 2020-01-08 14:48
Closing due to inactivity

**Closed by patrick96** 2020-01-08 14:48 UTC
Labels: needs confirmation

**Comment by VerySalted** [comment] 2020-09-20 14:36
Hi. I would like to reopen this issue. I am currently using Spectrwm and Polybar with the xworkspaces module in Arch. I saw that this problem was already reported and an issue was made so I didn't believe creating another one was necessary. 

This is what happens
- Before going to workspace 1, the label is `label-empty`
- I switch to workspace 1. Label now becomes `label-active`
- I open an application on workspace 1.
- I close the application on workspace 1. Now the workspace is empty. Label is still `label-active` because I am on workspace 1.
- I switch to another workspace. Workspace 1 label should now be `label-empty`, however, it shows as `label-occupied`.

Here is the module

```
[module/tags]
type = internal/xworkspaces

enable-click = true
enable-scroll = false

format = <label-state>

icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;ﭮ
icon-4 = 5;
icon-5 = 6;

label-monitor = %name%

label-active = %icon%
label-active-background = ${colors.background-tint-1}
label-active-foreground = ${colors.pink}
label-active-padding = 2

label-occupied = %icon%
label-occupied-foreground = ${colors.pink}
label-occupied-padding = 2

label-urgent = %icon%
label-urgent-foreground = ${colors.red}
label-urgent-padding = 2

label-empty = %icon%
label-empty-foreground = ${colors.foreground}
label-empty-padding = 2
```

And the bar
```
[bar/bar]
width = 100%
height = 32

override-redirect = true

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = "Roboto Mono:style=Medium:pixelsize=12;2:antialias=true:autohint=true"
font-1 = "RobotoMono Nerd Font:style=Regular:pixelsize=13;2"

tray-position = right

modules-left = tags title
modules-right = updates cpu filesystem memory volume date
```

Environment
```
❯ polybar -vv
polybar 3.4.0-116-gbb15e33

Features: +alsa +curl -i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/g++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags:
```

```
❯ spectrwm -v
spectrwm 3.4.1 Build: 3.4.1
```

If anything else is necessary to debug this, I will provide it.
