### ISSUE TITLE
Nerd Fonts Cut Off Characters, No Spacing, or overlapping

### ISSUE THREAD

**Issue by dieggsy** [polybar/polybar#991] opened 2018-02-02 06:27 UTC
## :exclamation::exclamation:Maintainer Note:exclamation::exclamation:
*I'm posting this here at the top so that people can immediately find it.*

When using [Nerd Fonts](https://nerdfonts.com) in polybar, many icons will either be cut off, overlap adjacent characters, or not have enough spacing after them.

There are several ways to work around this.

* Use a non-nerd fonts font for regular text and use the symbols-only variant (`Symbols Nerd Font Mono`) font as a second font for the icons because the symbols-only fonts don't have that issue. The symbols-only fonts are [released](https://github.com/ryanoasis/nerd-fonts/releases) in the file `NerdFontsSymbolsOnly.zip`.
* Use the monospaced version of the nerd font. For example if you are using `XYZ Nerd Font`, use `XYZ Nerd Font Mono` instead. This will make all icons the same width as regular text; they may appear too small though.
* Don't use Nerd Fonts. Nerd Fonts just pulls together multiple fonts, the individual fonts (material design icons, font awesome, etc.) don't have this issue as far as I can tell, using them directly should work.
* Manually add one or two extra spaces after every icon you are using. This is really not recommended.

For those interested in the details, read on.

What is happening is that when rendering an icon, our font rendering library (cairo) tells us how many pixels we should advance when rendering the next character.
In the non-mono versions of nerd fonts (except the symbols only variant) that is less than the actual width of the rendered icon.
This causes the icon to be cut off if there is a formatting tag after the icon.
In the other cases, the icon will overlap with the subsequent characters (missing spacing after icon is it simply overlapping with the spacing that should come after it).

This behavior is actually kind of intended according to nerd fonts, have a look at one of the maintainers' comments describing the situation: https://github.com/ryanoasis/nerd-fonts/issues/442#issuecomment-1263358904

---

**Original Post:**

I'm seeing this behavior with only a couple fontawesome characters:

![2018-02-02_01 27 27](https://user-images.githubusercontent.com/9020453/35719581-14687a6e-07b8-11e8-9b12-9355579ac9ee.png)

**Comment by patrick96** [comment] 2018-02-02 09:28
Does this also happen, if you lower the font size for the fonts those characters come from?

**Comment by dieggsy** [comment] 2018-02-02 14:39
@patrick96 oh interesting - it doesn't appear to

**Comment by patrick96** [comment] 2018-04-16 19:58
Hmm, I'm not able to reproduce this on my end. Is this with fontawesome 4 or 5?

**Comment by BVollmerhaus** [comment] 2018-06-14 16:45
I can reproduce this with both Font Awesome 4 (Nerd Fonts) and Material Design Icons, but only if the font size is set to an _odd_ number and fairly low, 11 in my case. On some icons this also appears to lead to some weird discoloration on the side where the character is cut off, see the example below.

![screenshot_2018-06-14_18-34-51](https://user-images.githubusercontent.com/30414540/41425661-b73d7b8e-7001-11e8-88f2-045dfb965b0f.png)
`mplus Nerd Font:style=Medium:size=10;3`

**Comment by ErMonao** [comment] 2019-11-21 22:07
Anyone able to solve this?

**Comment by patrick96** [comment] 2019-11-28 18:37
Can anybody that experiences this give me a minimal but complete config where this happens. I am still not able to reproduce this.

**Comment by NicksIdeaEngine** [comment] 2020-02-02 22:09
I can. Here are the config files: https://github.com/NicksIdeaEngine/dotfiles/tree/master/ubuntu/.config/polybar

I'm noticing the cutting off on the `launcher` and `sysmenu` module after trying to switch all the glyphs over to the ones from FiraCode Nerd Font.

The cutting off happens when I set `font-1` to size 12, 13, 14, 15, 16, all the way up to 20. I was aiming for size 14 or 16 and the rest of the glyphs seem to be working fine. I will try switching `module/launcher` and `module/sysmenu` to `type = custom/script` and see if that changes anything.

Here are screenshots:

![2020-02-02-170828_296x152_scrot](https://user-images.githubusercontent.com/7915199/73616220-bf22b300-45de-11ea-9666-3cab71a6a750.png)

![2020-02-02-170837_139x89_scrot](https://user-images.githubusercontent.com/7915199/73616223-c34ed080-45de-11ea-9b4b-af5d4ca2794b.png)

**Comment by fmauNeko** [comment] 2020-02-10 09:25
I'm having the same issue since the Nerd Font 2.1.0 release.
It's not happening with Nerd Font 2.0.0.

The fonts are working fine otherwise in my terminal (Tilix, which is based on VTE), so I guess it has something to do with how Polybar handles the glyphs.

**Comment by gavsiu** [comment] 2020-03-05 22:10
This was driving me nuts. Glad I found this bug report.

1 padding vs 0 padding:
![2020-03-05-140326_1920x1080_scrot](https://user-images.githubusercontent.com/806613/76030715-1d4afa80-5eeb-11ea-9a84-3d28e6b54c3c.png)

**Comment by georgianfire** [comment] 2020-03-20 14:01
@patrick96 Here is my config: https://gist.github.com/georgianfire/d5a27b5191fe4916e26afd2120bf003c
The last icon of `modules-left` is cut:
`modules-left = firefox vscode:`
![image](https://user-images.githubusercontent.com/62220669/77170176-0bdc2380-6a91-11ea-8d11-5279d6dde48d.png)

`module-left = vscode firefox`:
![image](https://user-images.githubusercontent.com/62220669/77170442-6d9c8d80-6a91-11ea-9703-a85ee7adb843.png)

As pointed out by @fmauNeko this only started happening after Nerd Fonts 2.1.0 release.

**Comment by collinpeters** [comment] 2020-04-13 06:26
https://github.com/ryanoasis/nerd-fonts/issues/442

**Comment by Saladaa** [comment] 2020-07-20 05:48
Wanna point out that this may not strictly be a nerdfont issue, I am having the same problem with the `Cozette` font (bitmap OTB type) in my bspwm workspace module:
![image](https://user-images.githubusercontent.com/29696609/87903570-a9774c00-ca9f-11ea-9511-206807ca1472.png)
It is most noticeable in the last two icons, where the headphone is cutoff at the headband and the film reel is missing the right side.

Using extra space padding before or after the icons does not help at all.

**Comment by shivanshu-semwal** [comment] 2020-12-16 17:04
Mono nerd fonts work fine in my case on i3.

**Comment by patrick96** [comment] 2020-12-16 17:13
@shivanshu-semwal What nerd fonts version and what distro are you using?

**Comment by shivanshu-semwal** [comment] 2020-12-16 18:30
> @shivanshu-semwal What nerd fonts version and what distro are you using?
- `Monoid Nerd Font Mono`  - [link](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Monoid)
- `Hack Nerd Font Mono` - [link](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack)
- `NotoSansMono` - [link](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Noto/Sans-Mono)
I'm using latest version of Nerd fonts available on the `nerd-font` repo. 
Distro - `Manjaro Linux x86_64`
![image](https://user-images.githubusercontent.com/53912074/102390645-af476e00-3ffa-11eb-9508-c0ec92dfa0ec.png)

`i3-module` is on left side and it is using Nerd Fonts.

**Comment by patrick96** [comment] 2020-12-16 22:55
Yeah, I have also noticed that using the monospaced version of the fonts does work properly. All the reports I have seen so far used the non-monospaced version.

**Comment by TheBabu** [comment] 2020-12-30 16:45
Do you guys think that this issue has anything related to this issue that I posted on notosans?
https://github.com/googlefonts/noto-fonts/issues/1960

**Comment by patrick96** [comment] 2020-12-30 16:57
@TheBabu I doubt it. The issue seems to be specific to nerd fonts.

**Comment by usarral** [comment] 2021-01-09 10:16
I have the same problem and I fixed with the Hack Nerd Font setting that the first

`;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ;-       fonts        -; ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

font-0 = "Hack Nerd Font:pixelsize=9;3"
font-1 = "Iosevka Nerd Font:pixelsize=10;3"
font-2 = "FontAwesome5:pixelsize=10;3"

font-3 = "Hack Nerd Font:pixelsize=23;5"
font-4 = "Iosevka Nerd Font:pixelsize=23;5"
font-5 = "FontAwesome5:pixelsize=23;5"

;;;;;;;;;;;;;;;;;;;;;;;;;;`

**Comment by defunSM** [comment] 2021-01-14 13:21
I had the one icon cut off when using Hack Nerd Font regardless of size padding or anything in polybar worked around it by using Hack Nerd Font Mono.

**Comment by defunSM** [comment] 2021-01-14 13:34
> I have the same problem and I fixed with the Hack Nerd Font setting that the first
> 
> ```
> ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
> ;; ;-       fonts        -; ;;
> ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
> 
> font-0 = "Hack Nerd Font:pixelsize=9;3"
> font-1 = "Iosevka Nerd Font:pixelsize=10;3"
> font-2 = "FontAwesome5:pixelsize=10;3"
> 
> font-3 = "Hack Nerd Font:pixelsize=23;5"
> font-4 = "Iosevka Nerd Font:pixelsize=23;5"
> font-5 = "FontAwesome5:pixelsize=23;5"
> 
> ;;;;;;;;;;;;;;;;;;;;;;;;;;
> ```

Did not work for me (using arch, bspwm, hack nerd font)
![image](https://user-images.githubusercontent.com/17814268/104597271-1d577300-5643-11eb-873e-8f6e07fe2af1.png)

I had one icon cut off when using Hack Nerd Font regardless of size padding or anything in polybar worked around it by using Hack Nerd Font Mono. However I don't like this work around and would like to use Hack Nerd Font is there any way to do this?

**Comment by AakashSharma7269** [comment] 2021-08-14 20:21
> > I have the same problem and I fixed with the Hack Nerd Font setting that the first
> > ```
> > ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
> > ;; ;-       fonts        -; ;;
> > ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
> > 
> > font-0 = "Hack Nerd Font:pixelsize=9;3"
> > font-1 = "Iosevka Nerd Font:pixelsize=10;3"
> > font-2 = "FontAwesome5:pixelsize=10;3"
> > 
> > font-3 = "Hack Nerd Font:pixelsize=23;5"
> > font-4 = "Iosevka Nerd Font:pixelsize=23;5"
> > font-5 = "FontAwesome5:pixelsize=23;5"
> > 
> > ;;;;;;;;;;;;;;;;;;;;;;;;;;
> > ```
> 
> Did not work for me (using arch, bspwm, hack nerd font)
> ![image](https://user-images.githubusercontent.com/17814268/104597271-1d577300-5643-11eb-873e-8f6e07fe2af1.png)
> 
> I had one icon cut off when using Hack Nerd Font regardless of size padding or anything in polybar worked around it by using Hack Nerd Font Mono. However I don't like this work around and would like to use Hack Nerd Font is there any other methods to try to resolve this besides the changing to Mono or lowering font size ( which doesnt work for me) to do this?

Faced this exact issue today, arch logo was cut off for me. Initially i thought it was a problem with my padding.

**Comment by Blugil** [comment] 2022-01-17 09:50
> > > I have the same problem and I fixed with the Hack Nerd Font setting that the first
> > > ```
> > > ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
> > > ;; ;-       fonts        -; ;;
> > > ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
> > > 
> > > font-0 = "Hack Nerd Font:pixelsize=9;3"
> > > font-1 = "Iosevka Nerd Font:pixelsize=10;3"
> > > font-2 = "FontAwesome5:pixelsize=10;3"
> > > 
> > > font-3 = "Hack Nerd Font:pixelsize=23;5"
> > > font-4 = "Iosevka Nerd Font:pixelsize=23;5"
> > > font-5 = "FontAwesome5:pixelsize=23;5"
> > > 
> > > ;;;;;;;;;;;;;;;;;;;;;;;;;;
> > > ```
> > 
> > 
> > Did not work for me (using arch, bspwm, hack nerd font)
> > ![image](https://user-images.githubusercontent.com/17814268/104597271-1d577300-5643-11eb-873e-8f6e07fe2af1.png)
> > I had one icon cut off when using Hack Nerd Font regardless of size padding or anything in polybar worked around it by using Hack Nerd Font Mono. However I don't like this work around and would like to use Hack Nerd Font is there any other methods to try to resolve this besides the changing to Mono or lowering font size ( which doesnt work for me) to do this?
> 
> Faced this exact issue today, arch logo was cut off for me. Initially i thought it was a problem with my padding.
> 
> I'm using the following `font-6=NotoSerif Nerd Font:style=Regular`

To me it looks like this specific error only happens when I use the `*-background` option on any module. Without a background the glyphs render perfectly. I am using `font-1=MesloLGS NF:style=regular:fixed:pixelsize=16;8`

**Comment by ARJITMALIK** [comment] 2022-03-01 16:35
Not possibly the solution, but I found an alternate method to counter this issue

I'm having extra padding issue with i3 workspace icons 
![156190870-fdb5f5a7-ed0e-4036-aff2-bd9614697efa](https://user-images.githubusercontent.com/76194457/156208829-67f50abb-1f69-417b-bc0f-f2587b883d85.png)

I just removed the background and underline and also added some foreground color to make the workspace stand out
![156205910-2486448b-f798-4672-91c8-5409fae68623](https://user-images.githubusercontent.com/76194457/156208994-bfd94b1a-db26-47da-949d-c8c99c78326b.png)

Im using the latest ```JetBrains nerd font``` and ```Font awesome 6 Brands``` fonts
```
font-0 = JetBrainsMonoMedium Nerd Font:style=Bold:size=14;4
font-1 = Font Awesome 6 Brands:size=14;4
```

Here is my [module/i3]
```
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = true

; Only show workspaces on the same output as the bar
pin-workspaces = true

ws-icon-0 = 1; 
ws-icon-1 = 2;
ws-icon-2 = 3; 
ws-icon-3 = 4; 
ws-icon-4 = 5; 
ws-icon-default = 

; label-mode = %mode%
; label-mode-padding = 5
; label-mode-foreground = #ffffff

label-mode-padding = 1
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %icon%
label-focused-background = ${colors.background}
label-focused-foreground = ${colors.green}
label-focused-padding = 1

; unfocused = Inactive workspace on any monitor
label-unfocused = %icon%
label-unfocused-padding = 1

label-visible = %icon%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %icon%
label-urgent-background = ${colors.background}
label-urgent-foreground = ${colors.alert}
label-urgent-padding = 1
```
(Great work with polybar, I'm loving it)

**Comment by patrick96** [comment] 2022-10-02 14:23
After talking to the nerd fonts maintainer I now have a better understanding of what is happening and why. I have edited the original post with the, in my opinion, best way to work around this issue.

I will also write up proper documentation about this for the 3.7 release.

**Comment by fiskhest** [comment] 2022-10-03 08:11
That seems to have done it 🎉  thanks for investigating @patrick96 ! 🚀

**Closed** 2023-09-30 17:32 UTC
Labels: font
