### ISSUE TITLE
More errors using openSUSE

### ISSUE THREAD

**Issue by devfoFikiCar** [polybar/polybar#2000] opened 2020-01-29 19:23 UTC
## Build Process
*Describe how you build polybar, list the exact commands you are using:*
./build.sh

**If you build polybar directly from this repository:**

* Output of `git describe --tags`:

**If you use some other way (like the AUR):**

*List exactly where you are building from and which version you are building.*
Newest from this repo

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*
```
** Fetching submodules

** A build dir already exists (pass -f to replace)

** Setting build options

** Use GCC even if Clang is installed ----------------------------- [y/N]: 

** Include support for "internal/i3" (requires i3) ---------------- [y/N]: 

** Include support for "internal/alsa" (requires alsalib) --------- [y/N]: 

** Include support for "internal/pulseaudio" (requires libpulse) -- [y/N]: 

** Include support for "internal/network" (requires libnl/libiw) -- [y/N]: 

** Include support for "internal/mpd" (requires libmpdclient) ----- [y/N]: 

** Include support for "internal/github" (requires libcurl) ------- [y/N]: 

** Build "polybar-msg" used to send ipc messages ------------------ [y/N]: 

** Parallelize the build using make -j4 --------------------------- [y/N]: 

** Using compiler: g++/gcc

** Executing cmake command

-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- No build type specified; using Release
-- Using supported compiler GNU-7.4.1
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.15.10
-- Checking for module 'xcb-composite'
--   Found xcb-composite, version 1.13
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.13
--  Build:
--    Version: 3.4.0-68-g3854fc9
--    Type: Release
--    CXX: /usr/bin/g++  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
--    LD: /usr/bin/ld  
--  Install Paths:
--    PREFIX:  /usr/local
--    BINDIR:  /usr/local/bin
--    DATADIR: /usr/local/share
--    DOCDIR:  /usr/local/share/doc/polybar
--    MANDIR:  /usr/local/share/man
--  Targets:
-- [ ]   polybar-msg
-- [ ]   testsuite
-- [ ]   documentation
--  Module support:
-- [ ]   alsa
-- [ ]   curl
-- [ ]   i3
-- [ ]   mpd
-- [ ]   network (wireless-tools)
-- [ ]   pulseaudio
-- [ ]   xkeyboard
--  X extensions:
-- [X]   xcb-randr (1.13)
-- [ ]   xcb-randr (monitor support)
-- [X]   xcb-composite (1.13)
-- [ ]   xcb-xkb
-- [ ]   xcb-xrm
-- [ ]   xcb-cursor
--  Log options:
-- [X]   Trace logging
-- The C compiler identification is GNU 7.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.13
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.14", minimum required is "2.7") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib64/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib64/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib64/libxcb-ewmh.so  
-- Could NOT find XCB_UTIL (missing: XCB_UTIL_LIBRARY XCB_UTIL_INCLUDE_DIR) 
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib64/libxcb-image.so  
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find XCB (missing: XCB_UTIL_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  lib/xpp/cmake/FindXCB.cmake:245 (find_package_handle_standard_args)
  lib/xpp/CMakeLists.txt:28 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/devfo/bar/polybar/build/CMakeFiles/CMakeOutput.log".
See also "/home/devfo/bar/polybar/build/CMakeFiles/CMakeError.log".
** Failed to generate build... read output to get a hint of what went wrong

```

## Environment:
* Distro (with Version):

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by patrick96** [comment] 2020-01-29 19:32
Duplicate of #1999

**Closed by patrick96** 2020-01-29 19:32 UTC
