### ISSUE TITLE
[Bug]: Wrong monitor listed with `polybar -m`

### ISSUE THREAD

**Issue by AlexanderLieret** [polybar/polybar#2679] opened 2022-04-06 10:24 UTC
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Connect two mirrored monitors
2. Start polybar with this script
    ```bash
    killall -q polybar
    for m in $(polybar -m | cut -d: -f1); do
      MONITOR=$m polybar --reload bar & disown
    done
    ```

### Minimal config

```dosini
[bar/bar]
monitor = ${env:MONITOR:}
width = 100%
modules-left = i3

[module/i3]
type = internal/i3
pin-workspaces = true
```

### Expected behavior

The open workspaces are shown on the left side of the bar.

### Actual behavior

Bar is empty.

```bash
$ polybar -M
eDP-1-1: 1920x1080+0+0
HDMI-1-2: 1920x1200+0+0

$ polybar -m
HDMI-1-2: 1920x1200+0+0
```

Starting polybar with `MONITOR=eDP-1-1` or without, shows the bar as expected.

### Window Manager and Version

i3 version 4.17.1 (2019-08-30)

### Linux Distribution

Ubuntu 20.04

### Polybar version

```text
polybar debian/3.6.2-1-dev

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Debian package, build flags removed from output for build reproducibility
You can refer to the build logs of your package at:
https://buildd.debian.org/status/package.php?p=polybar
```

### Additional Context / Screenshots

I compiled the Debian packages `3.5.5-1` and `3.6.2-1` for Ubuntu 20.04 by myself, both had the same problem. There is no Ubuntu 20.04 package available and the pre-build ones have newer dependencies.

After a quick look at the source code, I think the culprit is `randr_util::get_monitors` which removes the mirrored outputs.

**Comment by patrick96** [comment] 2022-04-06 11:14
Hi, this may be a duplicate of #499. Could you post the output of `i3-msg -t get_workspaces
` to confirm?

Since you are effectively using a single monitor (two physical monitors, but they display the same area), you can also just remove `pin-workspaces = true`, it is really only useful if you have monitors side-by-side.

**Comment by AlexanderLieret** [comment] 2022-04-06 12:22
I found a possible workaround. Query i3 for its output names.

```bash
i3-msg -t get_outputs | jq '.[] | select(.active).name'
```

**Comment by PandarinDev** [comment] 2022-04-11 14:12
I'm also affected by the same issue and I can confirm that your workaround from the last comment works for me just fine.

Output of `i3-msg -t get_workspaces | jq`
`[
  {
    "id": 94761185934752,
    "num": 2,
    "name": "2",
    "visible": true,
    "focused": true,
    "rect": {
      "x": 1920,
      "y": 35,
      "width": 1920,
      "height": 1045
    },
    "output": "HDMI-3",
    "urgent": false
  },
  {
    "id": 94761185931488,
    "num": 1,
    "name": "1",
    "visible": true,
    "focused": false,
    "rect": {
      "x": 0,
      "y": 35,
      "width": 1920,
      "height": 1045
    },
    "output": "DP-1",
    "urgent": false
  }
]`

**Comment by patrick96** [comment] 2022-04-11 19:29
> what causes this regression?

Could be a bunch of things. But if polybar fails to start it will print an error message. So if you redirect stderr in your script to some log file, you should be able to figure out why polybar didn't start.

**Closed** 2022-06-16 13:50 UTC
Labels: bug, needs confirmation
