### ISSUE TITLE
network module doesn't respect format-connected-foreground setting

### ISSUE THREAD

**Issue by gvlasov** [polybar/polybar#1599] opened 2019-01-13 07:45 UTC
## Describe the issue
Module `internal/network` doesn't respect `format-connected-foreground` setting

When I set 
```dosini
[module/wlan]
type = internal/network
format-connected-foreground = #000000
```
I expect the wlan widget to have black text on it.

Value from 
```
[bar/i3wmthemer_bar]
foreground = #ff0000
```
is used instead.

**Was it working before?**
This is the first time I'm using Polybar

## To Reproduce

Try changing `format-connected-foreground` for `internal/network` when foreground is set for the bar on which `internal/network` resides.

## Screenshots
Here I set bar's foreground to #ff0000, and network widget's colors to other colors. You can see that foreground color for network widget is #ff0000.

![Changed settings](https://user-images.githubusercontent.com/4467948/51082785-dbcc1e80-172f-11e9-949f-b29bd37f9fe4.png)

## Environment:
* WM: i3 with polybar theme from https://github.com/unix121/i3wm-themer
* Output of `polybar -vvv`:
```
➜ polybar -vvv
polybar 3.3.0-12-g46b8bb8

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/g++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags:

```

**Comment by patrick96** [comment] 2019-01-13 19:48
I can't reproduce this with the snippets you have given, please provide the config for the entire module as well as the entire bar section.

**Comment by gvlasov** [comment] 2019-01-14 05:03
@patrick96 Here's my complete config:

```dosini
[bar/i3wmthemer_bar]
width = 100%
height = 25
radius = 0
fixed-center = true

background = #1d1e26
foreground = #b0b287

line-size = 3
line-color =

border-size = 0
border-color =

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = "Source Code Pro Semibold:size=10;1"
font-1 = "Font Awesome 5 Free:style=Solid:size=10;1"
font-2 = "Font Awesome 5 Brands:size=10;1"

modules-left = wlan 
modules-center = 
modules-right = battery temperature memory cpu date

tray-position = center
;tray-padding =

cursor-click = pointer
cursor-scroll = ns-resize

[module/temperature]
type = internal/temperature
interval = 2

[module/memory]
type = internal/memory
interval = 3
label = MEM %mb_used%

[module/cpu]
type = internal/cpu
interval = 0.5
label = CPU %percentage%%

[module/battery]
type = internal/battery
interval = 10
label-charging = C🔋%percentage%
label-full = F🔋%percentage%
label-discharging = D🔋%percentage%

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-mode-padding = 2
label-mode-foreground = #1d1e26
label-mode-background = #1d1e26

label-focused = %index%
label-focused-background = #789073
label-focused-foreground = #1d1e26
label-focused-padding = 2

label-unfocused = %index%
label-unfocused-background = #789073
label-unfocused-foreground = #1d1e26
label-unfocused-padding = 2

label-visible = %index%
label-visible-background = #789073
label-visible-foreground = #1d1e26
label-visible-padding = 2

label-urgent = %index%
label-urgent-background = #BA2922
label-urgent-padding = 2

[module/wlan]
type = internal/network
interface = wlp3s0
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-foreground = #1d1e26
format-connected-background = #789073
format-connected-padding = 2
label-connected = %essid%

format-disconnected =

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = #1d1e26

[module/eth]
type = internal/network
interface = enp2s0
interval = 3.0

format-connected-padding = 2
format-connected-foreground = #1d1e26
format-connected-background = #789073
format-connected-prefix = " "
format-connected-prefix-foreground = #1d1e26
label-connected = %local_ip%

format-disconnected =

[module/date]
type = internal/date
interval = 5

date =
date-alt = " %Y-%m-%d"

time = %H:%M
time-alt = %H:%M:%S

format-prefix = 
format-foreground = #1d1e26
format-background = #789073
format-padding = 2

label = %date% %time%

[settings]
screenchange-reload = true

[global/wm]
margin-top = 0
margin-bottom = 0
```

**Comment by patrick96** [comment] 2019-01-14 22:10
Ah yes, just as I thought. This is a bug in how polybar handles colors inside a module, you have set `ramp-signal-foreground = #1d1e26` and polybar generates formatting tags so that after the ramp is finished, the foreground gets reset (because you don't want to have the ramp foreground). The problem is that the foreground always gets reset to the bar foreground (not to the format foreground). This is a known issue (see #598, #937). I'm actually working on a proposal to fix this.

For now the way I would suggest to fix this is to set
```dosini
format-connected = <ramp-signal> %{F#1d1e26}<label-connected>                                                                      
```
This forces polybar to set the foreground color directly before the label.

**Comment by patrick96** [comment] 2020-05-15 15:40
Closing in favor of #937

**Closed by patrick96** 2020-05-15 15:40 UTC
Labels: confirmed, duplicate
