### ISSUE TITLE
Positioning the system tray relative to other modules

### ISSUE THREAD

**Issue by flakyhermit** [polybar/polybar#2149] opened 2020-07-23 09:12 UTC
I think the ability to position the system tray to the left of all modules on the right side of the bar (or vice versa) should be available by default. Or else it should be possible to treat the tray like any other module so that it can be added to `module-{left, center, right}`.

## Why does polybar need this feature?
I suppose like myself a lot of people might wanna do the same thing. When I am moving my mouse cursor to a corner, I don't expect to open my Dropbox folder. Rather, I want something like a show desktop module or a power menu to be there. Isn't this the default way all the panels of desktop environments are organized? Shouldn't the user be atleast given a choice to get a similar result with polybar?

## Describe the solution you'd like
A configuration option like `tray-relative-position`.

**Comment by schspa** [comment] 2020-08-05 14:57
I want this feature too.

**Comment by thel-rico** [comment] 2020-08-26 18:37
I want it too ! I think it should be an internal module like others so we can define a module (eg with type = internal/systray) for configuration and thus we could place it in our bar like any other module

**Comment by unihernandez22** [comment] 2020-10-10 03:53
Yes, tray should be a module

**Comment by danielnehrig** [comment] 2020-10-13 05:31
> Yes, tray should be a module
tray should either be a module or behave like one
i don't understand the design decision why it is not a module tbh
maybe the tray integration was a thing before modules came around in polybar

**Comment by patrick96** [comment] 2020-11-27 22:40
I'm going to mark this as a duplicate of #314 

The reason the systray is not a module is because it doesn't behave like one. Everything in polybar is based on a sequence of text and formatting tags, except for the tray. The tray is a set of windows, *rendered* by the applications that provide tray icons, polybar just positions these windows correctly, relative to each other.

**Closed by patrick96** 2020-11-27 22:40 UTC
