### ISSUE TITLE
Blocks get under systray even when there is free space in the bar

### ISSUE THREAD

**Issue by roobre** [polybar/polybar#1838] opened 2019-07-24 10:26 UTC
## Is your feature request related to a problem? Please describe.

When one of the blocks (namely `modules-right`) grows too  big, it starts to "get under" the system tray, hiding the rightmost module. However, there is plenty of space between the leftmost module and the `modules-left` block. I don't know if this is due to some maximum sizes or padding being forced, but I think it would be great to be able to configure this.

Correctly displayed bar: 
![DeepinScreenshot_select-area_20190724122213](https://user-images.githubusercontent.com/969721/61786637-6c399900-ae0e-11e9-91f3-aff7c2fea13d.png)

Overlapping the tray:
![DeepinScreenshot_select-area_20190724122241](https://user-images.githubusercontent.com/969721/61786647-722f7a00-ae0e-11e9-9286-136f88e8194f.png)

As it can be seen, there is still plenty of space between `modules-right` and `modules-left`. Why is it not being used?

## Why does polybar need this feature?
Current behavior looks bad and wastes space.

## Describe the solution you'd like
I don't know exactly the root cause of this, but the user should be able to define its own margins, paddings, or minimum widths to avoid this effect. Or maybe this are just hardcoded values set too high and can be fixed without user configuration.

**Comment by Lomadriel** [comment] 2019-07-24 10:32
This is mostly a problem because the systray is quite buggy and isn't a module.
If I'm not wrong, there is no spacing between the blocks so we can't add this option.

**Comment by roobre** [comment] 2019-07-24 10:44
You are right, if I try to add even more modules to the right what I observe is:
![DeepinScreenshot_select-area_20190724124135](https://user-images.githubusercontent.com/969721/61787660-8d02ee00-ae10-11e9-992d-1e152435b5b8.png)

However, I do not understand this behavior. If this space can be shrunk further, why are we seeing three "phases", where space is taken from the left up to a certain point, then from the right (systray), and then from the left again? It does not make much sense to me.

**Comment by Lomadriel** [comment] 2019-07-24 10:58
The systray isn't polybar. It's a window placed over polybar, because of that we have many problems.
Our current plan is to remove this "temporary" solution and make the systray a real module, once done this problem should be solved. However this is a lot of works, we have to support images in the bar then we have to implement the systray (this isn't trivial :/). If I remember well, there are two systray protocols on Linux but I don't know how it works.

Without the systray, the right block should be hooked on the right and extend on the left. The left block works the same. For the center block this is a little more complicated.

With the systray, the end of polybar should be at the left of the systray but sometimes this is bugged and the end of the bar is under the systray :/

**Comment by roobre** [comment] 2019-07-24 13:00
Thank you very much for the detailed explanation. I understand then that detecting this case while using the current (temporary) implementation is non-trivial, just as migrating to a better implementation.
I'll try to workaround it somehow by reducing the number of modules or something. Thanks again for taking the time to explain it.

**Comment by Lomadriel** [comment] 2019-07-24 13:09
>  I understand then that detecting this case while using the current (temporary) implementation is non-trivial

Honestly, I don't know, I haven't worked on this portion of polybar. I'll take a look if I can do something.

**Comment by roobre** [comment] 2019-07-24 14:01
Please ping me if I can be of any help. Thanks!

**Comment by patrick96** [comment] 2019-10-15 14:04
@Lomadriel isn't this a duplicate of #591?

**Comment by roobre** [comment] 2019-10-15 14:33
For me this behavior is only happening when space taken by modules reaches a certain value, it never happens when, for example, only half of the space is being used. I'm not sure if it is the same bug.

**Comment by patrick96** [comment] 2019-10-15 14:36
Hmm oke, let's track this as a separate issue

**Comment by roobre** [comment] 2019-10-15 14:40
I can of course check for reproducibility again if 591 is fixed :)
Thanks for keeping track of this!

**Comment by patrick96** [comment] 2019-10-15 15:07
I would appreciate that :)

But chances are it is still not fixed since many people still have issues :disappointed:

**Comment by claudemuller** [comment] 2019-12-10 13:13
@patrick96 we discussed this issue on IRC and I said I would test your latest fix that hasn't made it to master yet.. I haven't tested it, but I noticed something that may help, I don't know.

So I have 3 x 27" monitors at 1080p that have around 4-5 workspaces on the left followed by the window title; nothing in the centre; some modules on the right and a tray with about 5 icons in it. The tray does not overlap anything on this desktop machine.

I also have a 14" laptop with a res of 1366x768 with 10 workspaces on the left followed by the window title; nothing in the centre; and the same setup as the desktop machine on the right. I recently shortened the polybar modules to have more space on the laptop and with that and a "crash" (of my own making) the laptop was only displaying 1 workspace - then the tray didn't overlap anything. But the minute I fixed the number of workspaces back to 10 it overlapped.

And fixed-center is set to false.

Don't know if that helps in any way :)

**Comment by patrick96** [comment] 2019-12-12 22:59
@roobre I may have a fix for #591 over at #1936. Would you mind testing it out? Looking at your description again it seems consistent with the issue in #591. What value for `fixed-center` were you using?

@claudemuller Hmm, unnecessary overlapping should not happen with `fixed-center = false`. How big was the gap between the left modules and the right modules when there was overlap? A gap of about 40 pixels is expected, anything else seems like a bug to me.

**Comment by roobre** [comment] 2019-12-13 09:29
Hi, thank you so much for the fix! Looks like I cannot reproduce the issue any longer! :tada: 

![DeepinScreenshot_select-area_20191213102700](https://user-images.githubusercontent.com/969721/70789378-341dfd00-1d93-11ea-9209-6d9d5f3a552a.png)

I'll test this during the day and report back here or in the PR if I encounter any unwanted side effect, although it seems to be working flawlessly now.

```ini
[roobre@Spinda]% ~> grep -e fixed-center .config/polybar/config
fixed-center = false
```

**Comment by patrick96** [comment] 2019-12-13 10:02
@roobre Thanks a lot for testing. Great to hear that it also fixed this :D

**Closed** 2019-12-21 14:43 UTC
Labels: bug, confirmed
