### ISSUE TITLE
Sphinx is not found while installing

### ISSUE THREAD

**Issue by im-n1** [polybar/polybar#1874] opened 2019-09-15 07:32 UTC
## Build Process
Standard compile process from readme - building from 3.4.0 tarball

## Environment:
* Debian testing

## Additional context
Once I use `sudo make install` it cannot find my Sphinx instalation which is installed via pip. When I run the command without sudo (just for testing purposes) Sphinx is found and does it's job - the instalation obviously fails because of no provileges to `/usr`.

![image](https://user-images.githubusercontent.com/198654/64918230-c1a17f00-d79b-11e9-8d07-8dbb6d6444f8.png)

Very dirty solution is to install Sphinx via apt but you don't want to have duplicated sphinx on your machine.

**Comment by Lomadriel** [comment] 2019-09-15 09:40
I don't really know how the python environment work but sphinx is only a build dependency for us so you can uninstall it after doing the `make install`.

**Comment by im-n1** [comment] 2019-09-15 15:55
I guess the thing is it's runnig sphinx under root (because of sudo) instead of the user you are spawning the command from. In such case it can't find sphinx and fails. The solution is to tell the part which handles docs to run sphinx under a user and then switch to root to be able to copy stuff into `/usr`.

Installing `python-sphinx` package is a workaround - dirty one.

**Comment by Lomadriel** [comment] 2019-09-15 16:10
Maybe running `make doc` before doing the `sudo make install` can solve your problem.

**Comment by im-n1** [comment] 2019-09-15 16:42
Just tried but didn't help

**Comment by patrick96** [comment] 2019-09-17 12:35
If that didn't help, the problem is likely not with you using sudo because `make install` doesn't run sphinx if you already ran `make doc`. Could you re-extract the tarball and compile polybar agains as follows:

* configure with `cmake` (generally `cmake ..` in the `build` folder)
* run `make -j`
* run `sudo make install`

and please post the output of this entire process here so that we can see where things go wrong.

**Comment by im-n1** [comment] 2019-09-17 13:19
I will try to do that asap.
Anyway the solution for now is to install `python3-sphinx`, run `sudo make install` and then run `apt purge python3-sphinx` and `apt autoremove` because of all the dependencies. I really hope some mess is not left on my drive.

**Comment by Lomadriel** [comment] 2019-09-17 17:27
> If that didn't help, the problem is likely not with you using sudo because `make install` doesn't run sphinx if you already ran `make doc`. Could you re-extract the tarball and compile polybar agains as follows:

I don't think that is true because it's a custom target. If I am not wrong CMake calls the custom target at every call.
See https://stackoverflow.com/questions/39895638/cmake-dont-build-project-again-when-executing-make-install.

The only solution I can think of is to generate the documentation at configure time (when `cmake ..` is called, like the `google-test` clone).

**Comment by patrick96** [comment] 2019-09-18 10:04
@Lomadriel you are correct. I'm not a fan of having build components run in the configure phase but it's also not optimal that sphinx is run as root when installing. I'll try to look around and see how other projects do it.

@im-n1 Can you make `pip` install sphinx globally to ` /usr/lib/python3.7/site-packages` instead of locally to your home directory?

**Comment by patrick96** [comment] 2019-09-18 10:25
You could also try setting `PYTHONPATH` to your user `site-packages` folder which could help with finding the packages when running as root.

I have dug around a bit in the cmake source code and they seem to also be running sphinx during `make install`, I'll try to reproduce this issue there as well and see what their solution is.

**Comment by patrick96** [comment] 2019-09-18 15:15
The cmake project has the same issue if you have sphinx only locally, they don't appear to have any solution for this (or aren't even aware of the problem).

I have found several ways to solve this:

* Run `make preinstall; sudo make -o preinstall install`. This does not build the `preinstall` target (which runs sphinx) as root
* Run `sudo PYTHONPATH="/home/n1/.local/lib/python3.7/site-packages" make install`. This way the sphinx python library can be found by root.
* Install locally with `mkdir pkg; DESTDIR=pkg make install`. And then copy the files there into your file system: `cd pkg; sudo cp -r usr /`.

The first one relies on cmake doing all the work in `preinstall` and using `install` only for copying files, don't know how futureproof that is.

The second one is a bit dirty because you still run sphinx as root but it should work as long as the paths don't change.

The third one is probably the most futureproof and is basically what cmake does internally as well.

Instead of solving the problem of how to get this to work with a local sphinx installation, I would recommend you install sphinx globally using pip, this would solve all your issues.

**Comment by patrick96** [comment] 2020-01-08 14:53
I am closing this.

We will not change polybar's build workflow for this and I have outlined multiple possible solutions to the problem above.

**Closed by patrick96** 2020-01-08 14:53 UTC
Labels: build
