### ISSUE TITLE
Handle system tray as a module

### ISSUE THREAD

**Issue by rubycasey** [polybar/polybar#2468] opened 2021-07-14 17:04 UTC
## Is your feature request related to a problem? Please describe.
Trays not getting rounded, not as easily fitting in with themes, not being able to be placed on the left of right-aligned modules, etc.

## Why does polybar need this feature?
Instead of having to go through and fix all these individual issues, I would imagine making a module out of it instead would make it integrate a lot easier, and being able to set underlines or place it in any position would help a lot with theming.

## Describe the solution you'd like
Create a system tray module, instead of handling system tray separate from the modules.

**Comment by patrick96** [comment] 2021-07-14 20:01
Duplicate of #314

**Closed by patrick96** 2021-07-14 20:01 UTC
