### ISSUE TITLE
Make tray icon backgrounds blur

### ISSUE THREAD

**Issue by catzybluphish** [polybar/polybar#1742] opened 2019-04-12 13:30 UTC
I'd like the tray icon backgrounds to have pseudo blur. It looks inconsistent when the rest of the bar is perfectly blurred. 
![2019-04-12-232409_1920x1080_scrot](https://user-images.githubusercontent.com/40843060/56040873-c2f8f680-5d7a-11e9-86e6-8f064ddf3bb9.png)
Thanks.

**Comment by patrick96** [comment] 2019-04-12 13:32
Are you using a compositor?

**Comment by catzybluphish** [comment] 2019-04-12 13:33
> Are you using a compositor?

Yes, compton.

**Comment by patrick96** [comment] 2019-04-12 14:23
@bennofs Could this be because we always use pseudo-transparency for the tray?

**Comment by patrick96** [comment] 2019-04-12 14:25
@catzybluphish How did you configure the tray and how did you configure the compton blur?

**Comment by bennofs** [comment] 2019-04-12 14:52
> @bennofs Could this be because we always use pseudo-transparency for the tray?

Yes, that should be the reason. Pseudo-tranparency will of course not get compton-blurred because we calculate the blending ourselves.

**Comment by patrick96** [comment] 2019-04-12 15:16
@bennofs I noticed that even if I set `pseudo-transparency = true` and compton is running, the bar is still blurred while the tray is not. Is there something else we do differently when handling transparency in the tray?

**Comment by catzybluphish** [comment] 2019-04-12 22:45
> @catzybluphish How did you configure the tray and how did you configure the compton blur?

[Compton](http://ix.io/1G24) | [Polybar](http://ix.io/1G25)
Should've clarified that I'm using tyrone's fork of compton with kawase blur.

**Comment by mvrozanti** [comment] 2020-01-04 21:21
I think I have the same problem, but mine just goes full transparent, with or without `pseudo-transparency = true`: 
![image](https://user-images.githubusercontent.com/11381662/71771736-fab65880-2f1e-11ea-8255-937f702fd65c.png)

**Comment by ShinysArc** [comment] 2020-04-11 19:12
> > @catzybluphish How did you configure the tray and how did you configure the compton blur?
> 
> [Compton](http://ix.io/1G24) | [Polybar](http://ix.io/1G25)
> Should've clarified that I'm using tyrone's fork of compton with kawase blur.

I know the issue is a bit old, but I'm currently struggling to make my polybar blurry, I'm also using tryone's fork of compton and using kawase blur. Everything is actually blurred except the bar, do you know where it could come from?

**Comment by patrick96** [comment] 2020-04-13 23:34
@ShinysArc So the bar is not blurred, not just the tray? You probably have polybar (or something like dock) in an exclude rule.

**Comment by semente** [comment] 2020-06-04 22:37
Hey, if I set tray-background to `#33000000` it won't work but if I use `33000000` it works.

**Comment by semente** [comment] 2020-06-04 23:02
> Hey, if I set tray-background to a variable such as`${color.bg}` it looks inconsistent like yours but if I use the code string like `#33000000` it works.

And I could reproduce it only when I have the `nm-applet` open. Otherwise using `${color.bg}` works fine. Weird.

**Comment by PoSayDone** [comment] 2020-08-20 16:50
Any solve of this thing?

**Comment by CosmicPegasis** [comment] 2020-09-07 13:01
Yes I'm having the same issue.
Neither of the techniques discussed work.

**Comment by CosmicPegasis** [comment] 2020-09-07 13:11
So I didn't get the blur to work but I did get it uniform with the system tray.
I did this by excluding polybar in my compositor config. I don't know how polybar works(I haven't read the code) but I think it has some problem rendering Kawase Blue and is thus reverting to default settings. So untill this is fixed you might just have to live without blur.
I would like to again state take everything I say with a grain of salt. I could probably be missing a really straight forward config option in the config file which enables said feature.

**Comment by phuhl** [comment] 2022-04-25 14:16
I have the same issue but it looks even weirder because I do have a border arround everything (that is blurred) which contrasts to the lack of blur of the tray:

![image](https://user-images.githubusercontent.com/16835755/165107360-3f41507b-97a6-4e39-a294-44b6c7267f8d.png)

**Comment by patrick96** [comment] 2022-11-07 20:28
Yeah, the pseudo-transparency prevents compton from blurring (because there is nothing to blur). From my investigations in #2609 I decided to not attempt adding true transparency for tray icons, it is considerably more complicated than transparency for the bar window and not worth the effort right now (at least not for me, maybe it is for someone more experienced in this area).

Because of that I will close this as wontfix.

**Closed by patrick96** 2022-11-07 20:28 UTC

**Comment by dkaszews** [comment] 2025-08-14 12:40
Unfortunately picom has the same issue:

<img width="181" height="39" alt="Image" src="https://github.com/user-attachments/assets/f2c7d22f-2f2c-40de-a27e-616a487d3130" />
