### ISSUE TITLE
All elements of format-volume after <bar-volume> do not have format-volume-background applied.

### ISSUE THREAD

**Issue by jp1995** [polybar/polybar#2321] opened 2020-12-21 11:15 UTC
## Checklist
* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
Using the pulseaudio module, elements that come after `<bar-volume>` in `format-volume` do not get the `format-volume-background` color applied to them. Instead, the background is simply transparent (showing the bar color below).

**Expected behavior:**
All elements given in `format-volume` get a background color.

**Actual behavior:**
`format-volume = <bar-volume> <label-volume>`
results in:
![2020-12-21_12-34-52_0](https://user-images.githubusercontent.com/8545997/102767953-0a75b980-4389-11eb-9a62-017a3aca0cb4.png)
`format-volume = "test <label-volume> test <bar-volume> test"`
results in:
![2020-12-21_12-36-59_0](https://user-images.githubusercontent.com/8545997/102768090-414bcf80-4389-11eb-8711-2a02c80e9e05.png)

**Was it working before?**
Not to my knowledge.

## To Reproduce
```dosini
[bar/main]
bottom = false
background = #25232A
foreground = #3C3836
font-0 = Mono 12
font-1 = Font Awesome:size=10;2
modules-right = pulseaudio


[module/pulseaudio]
type = internal/pulseaudio
interval = 10
format = <label>
label-volume = 
format-volume-background = #E8CB93

format-volume = <bar-volume> <label-volume>

bar-volume-width                = 8
bar-volume-gradient             = false
bar-volume-indicator            = 
bar-volume-indicator-foreground = #25232A
bar-volume-fill                 = 
bar-volume-fill-foreground      = #25232A
bar-volume-empty                = 
bar-volume-empty-foreground     = #25232A
bar-volume-background           = #E8CB93
bar-volume-empty-background     = #E8CB93
bar-volume-fill-background      = #E8CB93
bar-volume-indicator-background = #E8CB93
```
## Polybar Log
Nothing relevant
```
warn: No monitor specified, using "HDMI-A-0"
warn: pulseaudio: using default sink alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.mono-chat
```

## Environment:
* WM: i3
* Distro: manjaro
* Output of `polybar -vvv`:

```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context
The problem initially arose when I was trying to get padding to work with the volume bar. I tried to apply padding to the volume bar itself, which didn't do anything, as well as to the individual volume bar components, which predictably did not work well. Eventually I discovered this bug trying to just put a space after the `<bar-volume>` but the background color was broken at the space position.

**Comment by patrick96** [comment] 2020-12-21 12:12
Duplicate of #937

This is a larger issue with how polybar uses the lemonbar formatting tags.
labels (and ramps, bars etc) that have explicit colors set will reset that color to the bar color at the end.

This is what's happening here. `bar-volume-fill`, `bar-volume-indicator`, and `bar-volume-empty` all reset the background color to the bar background color and this color is then used by the subsequent label.

In your case there is a fix, remove these four lines:

```
bar-volume-background           = #E8CB93
bar-volume-empty-background     = #E8CB93
bar-volume-fill-background      = #E8CB93
bar-volume-indicator-background = #E8CB93
```

Since the format background is the same as the background you set here, this works. If you had a different background for the progressbar, then this is of course not viable. In that case, a workaround would be to also explicitly set the background color on `label-volume`.

**Closed by patrick96** 2020-12-21 12:12 UTC
