### ISSUE TITLE
Polybar Network module does not detect USB tethering 

### ISSUE THREAD

**Issue by J0eKing** [polybar/polybar#2234] opened 2020-11-01 18:12 UTC
## Describe the issue

When i connect my pc to my phone using USB tethering, polybar incorrectly recognizes the network as disconnected

**Expected behavior:**

I expect the polybar network module to display the USB network the same as my ethernet

**Actual behavior:**

Polybar detects network as disconnected. It says it cannot query the interface.

**Was it working before?**

no

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/topmain]
monitor =
monitor-fallback =
monitor-strict = false
override-redirect = false
bottom = false
fixed-center = true
wm-restack = bspwm
enable-ipc = true
width = 100%
height = 22
offset-x = 0%
offset-y = 0%
background = ${color.bground}
foreground = ${color.fground}
padding = 0
module-margin-left = 0
module-margin-right = 0
modules-right = d5 cpu s5 d4 memory s4 d3 network s3 d2 pulseaudio s2 d1 date

[module/network]
type = internal/network
interface = ${env:DEFAULT_NETWORK_INTERFACE:eno1}
interval = 1.0
accumulate-stats = true
format-connected = <ramp-signal> <label-connected>
format-connected-background = ${color.l3}
format-connected-foreground = ${color.modulefg}
format-connected-padding = 1
format-disconnected = <label-disconnected>
format-disconnected-background = ${color.l3}
format-disconnected-foreground = ${color.modulefg}
format-disconnected-padding = 1
label-connected =  %upspeed:9%  %downspeed:9% 
label-disconnected = ﴿ %upspeed:9%  %downspeed:9% 
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
```

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
warn: module/network: Failed to query interface 'enp0s29u1u3'
warn: module/network: Failed to query interface 'enp0s29u1u3'
warn: module/network: Failed to query interface 'enp0s29u1u3'
warn: module/network: Failed to query interface 'enp0s29u1u3'
warn: module/network: Failed to query interface 'enp0s29u1u3'

```

## Screenshots
When using USB tethering
![2020-11-01_200615-231x20_scrot](https://user-images.githubusercontent.com/65903718/97810609-c6661280-1c7d-11eb-8e91-c71a8ba101f9.png)

When using Ethernet
![2020-11-01_200903-176x21_scrot](https://user-images.githubusercontent.com/65903718/97810655-35dc0200-1c7e-11eb-9e25-26747c31e7aa.png)

## Environment:
* WM: bspwm
* Distro: arch
* Output of `polybar -vvv`:
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 

## Additional context

i just installed libnl and recompiled polybar an hour ago thinking it would solve the problem. Previously i did not have libnl and it still did not work

**Comment by patrick96** [comment] 2020-11-01 18:45
USB adapters are often tricky. They often don't provide the same information as built-in adapters and tend to confuse the network module.

Can you do the following for me? (Of course when you are connected to your USB tether)
 
* Post the contents of the `/sys/class/net/enp0s29u1u3/operstate` file
* Does `/sys/class/net/enp0s29u1u3/wireless` exist?
* Post the output of the commands `ethtool enp0s29u1u3`, `iw dev enp0s29u1u3 link` and `ip addr show`

This will help us narrow down where exactly the issue is.
There is already a similar issue to this one: #1541, but there the problem was that the adapter only worked with wireless_tools (you said it didn't even work then).

My best guess as to what is happening here is that the adapter, even though it is wireless, presents itself as an ethernet connection but it doesn't have a linkspeed. The network module cannot detect the linkspeed and fails. If that is the case, then this is the same issue as #1211. That issue is already fixed but it has not been in any release yet.

**Comment by J0eKing** [comment] 2020-11-02 06:02
#### /sys/class/net/enp0s29u1u3/operstate
```
unknown
```

 /sys/class/net/enp0s29u1u3/wireless does not exist

#### ethtool enp0s29u1u3
```
netlink error: Operation not permitted
Settings for enp0s29u1u3:
        Current message level: 0x00000007 (7)
                               drv probe link
	Link detected: yes

```
#### iw dev enp0s29u1u3 link
```
command not found: iw
```
#### (after installing iw)iw dev enp0s29u1u3 link
```
Not connected.
```
#### ip addr show
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 44:37:e6:a9:f4:ce brd ff:ff:ff:ff:ff:ff
    altname enp0s25
4: enp0s29u1u3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 12:4a:c7:9b:a0:d2 brd ff:ff:ff:ff:ff:ff
    inet 192.168.42.237/24 brd 192.168.42.255 scope global dynamic noprefixroute enp0s29u1u3
       valid_lft 3138sec preferred_lft 2688sec
    inet6 fe80::19a2:62b:e0eb:9686/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by J0eKing** [comment] 2020-11-02 06:17
You mentioned that it'd been fixed and that a release was not made yet.
Installing polybar-git from the AUR seems to have fixed the problem. Should I close the issue?

**Comment by patrick96** [comment] 2020-11-02 08:45
In that case, this is indeed a duplicate of #1211

**Closed by patrick96** 2020-11-02 08:45 UTC
