### ISSUE TITLE
[Bug]: `radius` does not round the tray.

### ISSUE THREAD

**Issue by allusive-dev** [polybar/polybar#3026] opened 2023-10-20 09:16 UTC
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Run polybar with config

### Minimal config

```dosini
radius = 10

tray-position = left

tray-detached = false

tray-maxsize = 16

tray-background = ${color.background}

tray-offset-x = 0
tray-offset-y = 0

tray-padding = 2

tray-scale = 1.0
```
```


### Polybar log

_No response_

### Expected behavior

Bar is rounded all the way round.

### Actual behavior

The rounding does not extend to the system tray.

### Window Manager and Version

XMonad 0.17.2

### Linux Distribution

NixOS 23.05

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /nix/store/lcf37pgp3rgww67v9x2990hbfwx96c1w-gcc-wrapper-12.2.0/bin/g++
Compiler flags:  -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags:  -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

### Additional Context / Screenshots

![image](https://github.com/polybar/polybar/assets/99632976/7e9e9273-80e1-4839-a783-0ec0af0a90f7)

**Comment by patrick96** [comment] 2023-10-20 10:06
Duplicate of #651

**Closed by patrick96** 2023-10-20 10:06 UTC
Labels: bug, needs confirmation
