### ISSUE TITLE
Click command not executed when it produces output.

### ISSUE THREAD

**Issue by johanmalm** [polybar/polybar#916] opened 2017-12-22 22:01 UTC
When creating a polybar "button" for [jgmenu](https://github.com/johanmalm/jgmenu), I came upon the issue described below. I'd be grateful for a steer on if it is the intended behaviour and if there is anything I could do to avoid it.

I use
  * polybar v3.1.0 (build from Arch AUR two days ago)
  * i3 v4.14.1
  * Arch Linux

Using the default polybar config file (/usr/share/doc/polybar/config), I added:
`modules-left = jgmenu bspwm i3`
and

```
[module/jgmenu]
type = custom/script
label-padding = 2
interval = 10
exec = echo "menu"
click-left = "jgmenu_run &"
```

I found that "jgmenu_run" and "jgmenu" work in terms of launching jgmenu. However, when running jgmenu as a long-running application (default), I don't get polybar back (as described on wiki, so nothing strange about that).

However, "jgmenu_run &" and "jgmenu &" do not launch jgmenu. This is what's peculiar to me. These commands work from the terminal with the "&".

I found that the following works:
`click-left = "jgmenu_run >/dev/null 2>&1 &"`

The issue can be re-created without jgmenu, by setting "click-left = ~/test.sh &" and then doing the following:

```
cat <<EOF >~/test.sh
#!/bin/sh
echo "foo"
dmenu_run
EOF
```

If the 'echo "foo"' line is removed, it works.

**Comment by natemaia** [comment] 2017-12-23 04:55
I'm pretty sure you dont want the menu being forked to the background

I have been using something like this
```
[module/jgmenu]
type          = custom/script
label         = %output%
label-padding = 2
interval      = 10
exec          = echo ""
click-left    = jgmenu_run lx
click-right   = exo-open $HOME/.config/jgmenu/jgmenurc
```

Making sure the following is set in ~/.config/jgmenu/jgmenurc
```stay_alive = 0```

Hope this helps

Nate

**Comment by johanmalm** [comment] 2017-12-23 14:13
Hi Nate 

Thanks for your quick response. Dobbie03 pointed me to your config, so that's what got me started  with polybar (thanks!). There can be some disadvantages of running jgmenu as a short-lived application (stay_alive=0):

  * On slow computers, there is a delay when starting a new instance (~200 ms on mine). Lots of effort has gone into making startup times quick, e.g. loading icons in a separate thread and caching icon paths. However, it will always be faster to awake an already running applications (with 'killall -SIGUSR1 jgmenu' or jgmenu_run).

  * If running without a compositor (e.g. compton), there is a noticable flicker when the X11 window  is first created and cairo starts drawing. Not a problem when stay_alive=1

  * lx and xdg are quite quick, but pmenu is slower as it invokes python. This is not a problem when used as a long-running application, but noticeable when short-lived.

* Lots of chewing of harddisk (i.e. icon and menu related files)

Either way, the polybar behaviour puzzles me.

In the case of dmenu_run (example above), I agree, there is no point in forking to background. But it's a simple example which makes it easier to reproduce the issue.

I have not looked at the polybar code. I can do, but guess it will be a lot quicker for the devs to get their heads around what going on. Maybe it's designed the way it is for a reason.

Johan

**Comment by natemaia** [comment] 2017-12-24 05:53
Yea, I do believe there is some reason, as polybar allows tailing of commands and execution at intervals..

With my little experience with it, I have noticed it behaves very oddly depending on the application
Check this
```
[module/menu]
type           = custom/menu
format-spacing = 1
label-open     = "    "
label-close    = "    "
label-close-foreground  = ${colors.urgent}
label-separator = " | "
# Top level
menu-0-0       = "  "
menu-0-0-exec  = menu-open-1
menu-0-1       = "  "
menu-0-1-exec  = menu-open-2
menu-0-2       = "    |"
menu-0-2-exec  = menu-open-3
# 1
menu-1-0       = "  "
menu-1-0-exec  = menu-open-0
menu-1-0-foreground = ${colors.urgent}
menu-1-1       = "  "
menu-1-1-exec  = exo-open --launch WebBrowser
menu-1-2       = "  "
menu-1-2-exec  = exo-open --launch TerminalEmulator
menu-1-3       = "    |"
menu-1-3-exec  = exo-open --launch FileManager
# 2
menu-2-0       = "  "
menu-2-0-exec  = menu-open-0
menu-2-0-foreground = ${colors.urgent}
menu-2-1       = "  "
menu-2-1-exec  = termite --exec=pacli &
menu-2-2       = "  "
menu-2-2-exec  = xfce4-settings-manager &
menu-2-3       = "    |"
menu-2-3-exec  = pavucontrol &
```

The purpose isnt to see my menu, just that notice exo-open apps will not work properly when trying to use ```&``` this causes some hard locking of the bar, however others like termite, and pavucontrol, will require ```&``` for them to NOT hard lock the bar.. It's all very strange

Cheers,

Nate

**Comment by patrick96** [comment] 2017-12-27 18:26
While testing this I have also noticed that the click command do not work as soon as they produce any sort of output, this is a bug and definitely not intended, but can easily be fixed by adding the already mentioned `&> /dev/null` to the commands. I will attempt to fix that part, but I'm not sure how long it will take, looking at the relevant code, I realize that I don't understand a lot of it.

As for the bar locking up, during my testing I have not seen anything that is out of the ordinary. It is however not quite intuitive. What polybar does, is it waits for the command to finish before doing anything else. So for example `pavucontrol` will only finish once its window is closed again, that's why polybar locks up, if you just have `click-left = pavucontrol`. 
On the other hand `exo-open ...` will always return immediately, that's why it doesn't lock up the bar. Where our results differ is when using `menu-0-0-exec = exo-open --launch TerminalEmulator &`, for me this works the same as without the `&`, whereas you say the bar locks up.
In general using `&` should always work. @natemaia Can you produce a minimal configuration using `exo-open` with `&` where the bar then locks up for you and open a new issue with it because this may be another unrelated bug

**Comment by johanmalm** [comment] 2017-12-27 21:53
Hi @patrick96 and thanks for the response.

Is there a reason to wait for `click-left =` commands to finish? Coud we just fork+exec?
Here is a simple example of how I did it in jgmenu.
[spawn()](https://github.com/johanmalm/jgmenu/blob/master/util.c#L55)

I don't think that `&>` is POSIX, so could lead to problems depending on what `sh` is set to.
A safer way is `>/dev/null 2>&1`

**Comment by natemaia** [comment] 2017-12-28 05:33
@patrick96 I believe you are correct 
My apologies, exo-open along with many others do NOT lock the bar when using ```&```
I cannot remember the exact instance it must have been with a different application, appending ```&```
alone caused the same previous mentioned issue

I can certainly try making a really simple config attempting to reproduce some of this
and give you the results back here.

@johanmalm You are correct ```&> /dev/null``` is not POSIX

**Comment by patrick96** [comment] 2018-09-11 16:12
@johanmalm I wasn't involved when the responsible code was written. Will probably rewrite parts of it to also not have polybar lock up when the command doesn't terminate.

**Comment by johanmalm** [comment] 2018-09-13 22:05
@patrick96 That's great. Let me know if I can help with anything.

**Comment by patrick96** [comment] 2018-09-13 22:43
Sure thing, thanks

**Comment by Lomadriel** [comment] 2019-03-06 23:32
When I tried to reproduce this bug I noticed something really strange.
On the following minimal config, impossible to reproduce the bug.
```
[bar/example]
width = 100%
height = 27

font-0 = fixed:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = siji:pixelsize=10;1

modules-left =
modules-center = bug_module
modules-right =

[module/bug_module]
type          = custom/script
label         = %output%
label-padding = 2
interval      = 100000000
exec          = echo "menu"
click-left = "~/test.sh >/dev/null 2>&1 &"
``` 

However on my full config, the bug is present. So I think there is somewhere some strange interactions between two modules… I will try to find the origin of this bug.

**Comment by Lomadriel** [comment] 2019-03-07 02:14
If I remove the following lines, it works but I don't know why…
https://github.com/jaagr/polybar/blob/25ef0299cb2bb835782d846a05695bcffc98b407/src/utils/command.cpp#L74-L76

**Closed** 2020-05-08 21:24 UTC
Labels: bug, confirmed
