### ISSUE TITLE
Double-width characters in bspwm module

### ISSUE THREAD

**Issue by gipert** [polybar/polybar#2093] opened 2020-05-09 13:32 UTC
Double-width glyphs in bspwm workspaces get truncated when status is 'focused'. I tried to tweak many module parameters but couln't get rid of it. Any Ideas on how to fix this?

**Was it working before?**
First time I try it.

## To Reproduce
```dosini
[bar/lxpertoldi_hor]
override-redirect = true
width = 100%
height = 27
offset-x = 0
offset-y = 0
radius = 0.0
fixed-center = false
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3
line-color = #f00
border-size = 4
border-color = ${colors.background}
padding-left = 0
padding-right = 2
module-margin-left = 1
module-margin-right = 2
font-0 = Fira Code:style=Regular:size=10;1
font-1 = 3270Medium Nerd Font:size=11;1
modules-left = bspwm-lxpertoldi
modules-center =
modules-right =
wm-restack = bspwm
cursor-click = pointer

[module/bspwm]
type = internal/bspwm
label-focused = %icon%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.ylw}
label-focused-padding = 1
label-occupied = %icon%
label-occupied-padding = 1
label-urgent = %icon%!
label-urgent-background = ${colors.red}
label-urgent-padding = 1
label-empty = %icon%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 1

[module/bspwm-lxpertoldi]
inherit = module/bspwm
ws-icon-0 = "I;I"
ws-icon-1 = "II;II"
ws-icon-2 = "III;III"
ws-icon-3 = "IV;IV"
ws-icon-4 = "V;V"
ws-icon-5 = "VI;VI"
ws-icon-6 = "VII;VII"
ws-icon-7 = "VIII;VIII"
ws-icon-8 = "IX;IX"
ws-icon-9 = "X;X"
ws-icon-10 = "XI;XI"
ws-icon-11 = "XII;XII"
ws-icon-12 = "XIII;XIII"
ws-icon-13 = "XIV;XIV"
ws-icon-14 = "XV;XV"
ws-icon-15 = "XVI;XVI"
ws-icon-16 = "XVII;XVII"
ws-icon-17 = "XVIII; "
ws-icon-18 = "XIX; "
ws-icon-19 = "XX; "
```

## Polybar Log
Nothing unusual here

## Screenshots
![Screen Capture_select-area_20200509151045](https://user-images.githubusercontent.com/20358192/81474686-6ed37680-9207-11ea-9e36-5ff8c98ca951.png)

## Environment:
* WM: bspwm
* Distro: Arch Linux
* Output of `polybar -vvv`:
```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context
I use Fira Code as main font and 3270-Medium Nerd Font Patched for the extra glyphs.

**Comment by patrick96** [comment] 2020-05-09 20:12
Duplicate of #991 

This seems to be a NerdFonts issue: https://github.com/ryanoasis/nerd-fonts/issues/442

**Closed by patrick96** 2020-05-09 20:12 UTC
