### ISSUE TITLE
Tray turns black (likely after fullscreen)

### ISSUE THREAD

**Issue by 132ikl** [polybar/polybar#789] opened 2017-10-05 01:36 UTC
Often my tray will turn black every once and a while. It's likely related to the way polybar handles fullscreen since it has to stop drawing the tray seperate from the regular bar. The cause is likely that the tray isn't being notified to draw again after fullscreen mode is exited. The only way to fix the issue is to kill and restart polybar.

**Comment by patrick96** [comment] 2017-10-06 14:41
Does the tray appear again, if you start or stop an application that adds a tray icon?

**Comment by 132ikl** [comment] 2017-10-06 15:08
No.

**Comment by drdeimos** [comment] 2017-10-08 14:26
I've get something like this with CopyQ tray icon and keepass2 icon.
He transform into black square
![efff9038a51403e00700adf8413caa2b4da3803e](https://user-images.githubusercontent.com/3472810/31317632-08f719b8-ac4d-11e7-98c8-5f28faa65291.png)

If i change offset-y in config - see icon stacked above panel 
![4ff1f2a932793698d8f71ff240341f67fdaec3f7](https://user-images.githubusercontent.com/3472810/31317654-87212aae-ac4d-11e7-8162-8c00d0ba5dc6.png)

**Comment by 132ikl** [comment] 2017-10-08 16:06
The image @drdeimos has posted is the exact same thing as what I'm experiencing.

**Comment by NBonaparte** [comment] 2017-10-08 16:29
For the keepass issue, see #545.

**Comment by bricewge** [comment] 2018-10-08 12:51
I have the exact same issue and can reproduce it with `polybar 3.2.1`. At first I thought setting `tray-background = ${colors.background}` would fix it but strangely it doesn't.

To reproduce:
1. `polybar --reload example`
2. `blueman-manager`
3. The systray then turn back and polybar log `error: Failed to query _XEMBED_INFO, removing client... (XCB_WINDOW (3))

Calling `pkill -USR1 polybar` will re-display the bar correctly and the error will not show.

**Comment by somospocos** [comment] 2019-07-06 07:10
I'm getting a black systray as well, with polybar-3.3.1 and default config.

Since my wm already has tray (I'm using dwm with the systray patch), if I run polybar, then an app that has a tray icon, it goes to dwm's systray (while polybar says that systray selection is already managed in console) - I am running polybar via Xephyr like this:

    xinit ~/tmp/.xinitrc -- /usr/bin/Xephyr :1 -screen 1368x500x24

the custom xinitrc runs fluxbox, which by default doesn't have a tray, and polybar at startup. When I start a program that has a tray icon, the tray turns black. I've tried with three different programs that have systray icons and the black systray persists for all of them, so this doesn't seem to be a problem of a particular program.

**Comment by patrick96** [comment] 2020-01-25 11:46
@132ikl What window manager are you using?

**Comment by 132ikl** [comment] 2020-01-25 22:03
i3-gaps

**Comment by patrick96** [comment] 2020-01-25 22:44
@132ikl Thanks. So this and #1995 are likely the same underlying issue, I have written about my findings over there.

**Comment by patrick96** [comment] 2023-03-25 21:12
This should be fixed by #2609 if you are using the new tray module.

**Closed** 2023-03-25 21:12 UTC
Labels: tray
