### ISSUE TITLE
PulseAudio module uses too much CPU time

### ISSUE THREAD

**Issue by lachs0r** [polybar/polybar#1943] opened 2019-11-28 22:36 UTC
## Describe the issue
When the PulseAudio module is loaded, polybar spends a disproportionate amount of CPU time. It also shows up in PowerTOP, consuming an extra 110-120 mW during the sampling interval.

With PA module:
```  120 mW      1,4 ms/s      39,7        Process        [PID 9607] polybar -r top```
Without:
```8.9 mW      2,7 ms/s      10,9        Process        [PID 9598] polybar -r top```

**Expected behavior:**

The PulseAudio module should not consume more power and CPU time than all other modules combined.

**Actual behavior:**

The PulseAudio module consumes more power and CPU time than all other modules combined.

**Was it working before?**

I don’t think so.

## To Reproduce
*A minimal but complete config with which the problem occurs:*

```dosini
[bar/top]
modules-right = snd

[module/snd]
type = internal/pulseaudio
```

## Environment:
* WM: i3
* Distro: openSUSE Tumbleweed
* Output of `polybar -vvv`:

```
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm -xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -DNDEBUG -Wall -Wextra -Wpedantic -O2 -g -DNDEBUG
Linker flags: -flto=4 -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now 
```

**Comment by patrick96** [comment] 2019-11-28 23:16
How long was the sampling interval? Did you sample mutliple times?

I can't look into this right now because I'm not at my laptop and my desktop doesn't show any wattage information in powertop. I have looked at the pulseaudio code and unless pulse generates hundreds of updates per second, the pulse module shouldn't really do all that much since it only does something when pulse itself signals a change.

**Comment by lachs0r** [comment] 2019-11-29 06:10
The interval was PowerTOP’s default of 20 seconds. I did sample multiple times and was able to reproduce this behavior across reboots and with a much more complex config than the minimal example.

What tipped me off was the `TIME` column in procps top, which showed a number that seemed much higher than it should be for a program like polybar. The PA module’s functions also seemed to show up in `perf top` with a slightly higher percentage than those of most other modules, but I didn’t investigate this further and just tried removing the module from my config.

**Comment by patrick96** [comment] 2019-12-02 16:16
Alright, I can't reproduce this at all on my system. It is possible that on your system we constantly get new pulse events and thus update the module 40 time a second.

Could you run a config with only the pulse module with info logging (`-l info`) and see how regularly you get the `Rebuilding cache` message for the pulse module. Normally you should only get that when the volume or the sink changes.

**Comment by x70b1** [comment] 2019-12-17 23:10
I cant reproduce this behavior. 

No modules (just one static text module):
```
199 uW     10,8 us/s      0,05        Process        [PID 48159] polybar top
```

All my modules (~ 20 modules and scripts), no PulseAudio:
```
121 mW      1,3 ms/s      30,6        Process        [PID 48410] polybar top
118 mW      1,3 ms/s      29,8        Process        [PID 48409] polybar top
117 mW      1,1 ms/s      29,7        Process        [PID 48420] polybar top
114 mW      1,2 ms/s      28,9        Process        [PID 48418] polybar top
109 mW      1,1 ms/s      27,6        Process        [PID 48419] polybar top
107 mW      1,2 ms/s      27,2        Process        [PID 48411] polybar top
```

All my modules (~ 20 modules and scripts), including PulseAudio:
```
 102 mW      1,5 ms/s      25,7        Process        [PID 49167] polybar top
 89.2 mW      1,3 ms/s      22,5        Process        [PID 49156] polybar top
 83.8 mW      1,1 ms/s      21,2        Process        [PID 49162] polybar top
 76.4 mW      1,3 ms/s      19,2        Process        [PID 49146] polybar top
 73.9 mW      1,4 ms/s      18,6        Process        [PID 49148] polybar top
 72.1 mW      1,3 ms/s      18,1        Process        [PID 49164] polybar top
```

All my modules (~ 20 modules and scripts), including PulseAudio and creating updates with a lot of volume changes:
```

69.3 mW      1,0 ms/s      17,5        Process        [PID 49167] polybar top
57.0 mW      7,9 ms/s      12,6        Process        [PID 49172] polybar top
45.7 mW    606,7 us/s      11,6        Process        [PID 49148] polybar top
43.5 mW    539,2 us/s      11,0        Process        [PID 49162] polybar top
39.9 mW    658,5 us/s      10,1        Process        [PID 49156] polybar top
37.9 mW    605,0 us/s       9,6        Process        [PID 49147] polybar top
37.7 mW    585,5 us/s       9,5        Process        [PID 49146] polybar top
35.8 mW    597,1 us/s       9,0        Process        [PID 49164] polybar top
```

It shows no clear picture. It shows the opposite.
But it confirms my experience with powertop. It is a nice tool to get an overview. But the power usage values are not exact.

**Comment by patrick96** [comment] 2020-01-08 15:26
I'm closing this. Neither of us can reproduce this and nothing in the pulse module actually does anything without pulseaudio itself signaling a change. On my machine such changes are only signaled when sinks or volumes or similar change. Even if pulse issues thousands of signal per second, I think that would be an issue with pulse rather than polybar.

**Closed by patrick96** 2020-01-08 15:26 UTC
