### ISSUE TITLE
Fcitx tray icon not showing in tray bar

### ISSUE THREAD

**Issue by Kiblyn11** [polybar/polybar#2479] opened 2021-08-14 15:27 UTC
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

I was using i3bar and switched recently to using polybar with https://github.com/adi1090x/polybar-themes. I am using Fcitx and icon which was showing in i3bar does not work in polybar.

**Expected behavior:**

Fcitx icon appears in tray.

**Actual behavior:**

Fcitx icon does not appears in tray.

**Was it working before?** No
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)? don't know
* If no, what was the last version where this worked correctly?

## To Reproduce

```
fcitx -D
polybar -q main -c "config.ini" &
```

Config here (not much changed from polybar-themes): https://www.file.io/download/JuebKvAGYCH9

## Polybar Log
```
error: Failed to query _XEMBED_INFO, removing client... (Invalid _XEMBED_INFO for window 0x1400706)
```

## Environment:
* WM: i3
* Distro: Arch linux
* Output of `polybar -vvv`:

```
polybar 3.5.6

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment] 2021-08-14 21:16
The error message suggests that fcitx doesn't configure its tray icon window correctly. So this seems to be a problem with fcitx.

There is also an issue (#2442) with the same error message that says that this is a regression and that polybar used to support the tray icon (even though it still printed the error message).

So either this is an issue with fcitx and polybar can't really do anything about it or the error should be non-fatal and then this is a duplicate of #2442. Either way, I'm closing the issue.

**Comment by patrick96** [comment] 2021-08-30 14:48
@Yugeniki Thanks for the heads-up, I'll have to look more closely into XEMBED then. Was this happening `fcitx` for you as well?

**Comment by Yugeniki** [comment] 2021-08-30 15:54
> @Yugeniki Thanks for the heads-up, I'll have to look more closely into XEMBED then. Was this happening `fcitx` for you as well?

Yes. Interestingly while fcitx 4.0.2 doesn't show up in tray, its newer version fcitx 5 does. So if anyone is having this problem I would recommend switching to fcitx 5 until this matter is settled. 

worth noting is that tray icon for fcitx when embeded in awesome, stalonetray, qtile, etc is different from the tray you get when you enable the snixembed. Something worth thinking about, maybe?

**Comment by patrick96** [comment] 2021-08-30 16:28
> worth noting is that tray icon for fcitx when embeded in awesome, stalonetray, qtile, etc is different from the tray you get when you enable the snixembed. Something worth thinking about, maybe?

That's probably because when you have `snixembed`, fcitx will use a completely different (and newer) way to provide a tray icon (StatusNotifierItem) and this new way may have updated icons while the legacy XEMBED tray icon still has an old one (or maybe themes affect them differently).

**Comment by patrick96** [comment] 2021-09-08 16:42
I was able to track down the issue. fcitx 4 does not support XEMBED. But looking at stalonetray, the system tray protocol can still work (even though it mandates XEMBED support) with some modifications.

I suspect this issue and #2442 are actually the same.

If you want, you can try out #2494 and see if that fixes it for you as well.

**Closed** 2021-09-21 16:23 UTC
