### ISSUE TITLE
[Bug]: Half of Icon Missing When Using Colored Background

### ISSUE THREAD

**Issue by samEngineering** [polybar/polybar#2738] opened 2022-06-10 21:29 UTC
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Make the following module using the 'Tux' icon with FontAwesome:

```
[module/tux]
type = custom/text
content = "  "
content-background = ${env:BLUE}
content-foreground = ${env:BACKGROUND}
content-padding = 2 
```

### Minimal config

```dosini
[global/wm]                                                                                                                                                                              
  margin-top = 0
  margin-bottom = 0
  
  
  
  [bar/main]
  enable-ipc = true
  monitor = ${env:MONITOR:}
  monitor-strict = false
  override-redirect = false
  wm-restack = ${env:DESKTOP_SESSION}
  bottom = false
  fixed-center = true
  width = 100%
  height = 25
  background = ${env:BACKGROUND}
  foreground = ${env:BACKGROUND}
  border-size = 0
  border-color = ${env:TRANSPARENT}
  
  font-0 = "FontAwesome:size=12;3"
  font-1 = "Noto Sans:size=12;3"
  font-2 = "Hack Nerd Font:size=13;3"
  
  modules-left = tux
  modules-center = bspwm
  modules-right = clock




  [module/bspwm]
  type = internal/bspwm
  pin-workspaces = true
  strip-wsnumbers = true
  index-sort = false
  enable-click = true                                                                                                                                                                      
  enable-scroll = true
  wrapping-scroll = false
  reverse-scroll = false
  fuzzy-match = false
  
  ws-icon-0 = 1;●
  ws-icon-1 = 2;●
  ws-icon-2 = 3;●
  ws-icon-3 = 4;●
  ws-icon-4 = 5;●
  ws-icon-5 = 6;●
  ws-icon-6 = 7;●
  ws-icon-7 = 8;●
  ws-icon-8 = 9;●
  ws-icon-default = ●
  
  label-focused = %icon%
  label-focused-foreground = ${env:MAGENTA}
  label-focused-background = ${env:BACKGROUND}
  label-focused-padding = 2
  
  label-occupied = %icon%
  label-occupied-foreground = ${env:GREEN}
  label-occupied-background = ${env:BACKGROUND}
  label-occupied-padding = 2

  label-empty = %icon%
  label-empty-foreground = ${env:GREEN}
  label-empty-background = ${env:BACKGROUND}
  label-empty-padding = 2
  
  label-urgent = %icon%
  label-urgent-foreground = ${env:GREEN}
  label-urgent-background = ${env:BACKGROUND}
  label-urgent-padding = 2     


  [module/clock]
  type = custom/script
  exec = zsh ~/.config/polybar/scripts/time.sh
  interval = 5
  click-left = ~/.config/polybar/scripts/date.sh
  format-prefix = " "
  format-prefix-foreground = ${env:BLUE}
  format-prefix-background = ${env:BACKGROUND}
  label = "%output%     "
  label-foreground = ${env:WHITE}
  label-background = ${env:BACKGROUND}



  [module/tux]
  type = custom/text
  content = "  "
  content-background = ${env:BLUE}
  content-foreground = ${env:BACKGROUND}
  content-padding = 2

```
```


### Polybar log

```text
notice: Parsing config file: /home/sam/.config/polybar/test.config
notice: Listening for IPC messages (PID: 31805)
notice: Parsing config file: /home/sam/.config/polybar/test.config
notice: Listening for IPC messages (PID: 31804)
notice: Loading module 'tux' of type 'custom/text'
notice: Loading module 'bspwm' of type 'internal/bspwm'
notice: Loading module 'clock' of type 'custom/script'
notice: Loaded 3 modules
notice: Loading module 'tux' of type 'custom/text'
notice: Loading module 'bspwm' of type 'internal/bspwm'
notice: Loading module 'clock' of type 'custom/script'
notice: Loaded 3 modules
notice: Loaded font "FontAwesome:size=12" (name=FontAwesome, offset=3, file=/usr/share/fonts/awesome-terminal-fonts/fontawesome-regular.ttf)
notice: Loaded font "Noto Sans:size=12" (name=Nimbus Sans, offset=3, file=/usr/share/fonts/gsfonts/NimbusSans-Regular.otf)
notice: Loaded font "Hack Nerd Font:size=13" (name=Hack Nerd Font, offset=3, file=/usr/share/fonts/hack-nerd-font/Hack Regular Nerd Font Complete.ttf)
notice: Loaded font "FontAwesome:size=12" (name=FontAwesome, offset=3, file=/usr/share/fonts/awesome-terminal-fonts/fontawesome-regular.ttf)
notice: Loaded font "Noto Sans:size=12" (name=Nimbus Sans, offset=3, file=/usr/share/fonts/gsfonts/NimbusSans-Regular.otf)
notice: Loaded font "Hack Nerd Font:size=13" (name=Hack Nerd Font, offset=3, file=/usr/share/fonts/hack-nerd-font/Hack Regular Nerd Font Complete.ttf)
```
```


### Expected behavior

Icon is rendered fully

### Actual behavior

half rendered

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

archlinux 5.15.44-1-lts

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

### Additional Context / Screenshots

![polybar-error](https://user-images.githubusercontent.com/93288460/173153630-dde3223f-4c48-4e21-a528-26029d9a0267.png)

**Comment by patrick96** [comment] 2022-06-12 15:03
Duplicate of #991

This is a long standing bug in nerd fonts.

**Closed by patrick96** 2022-06-12 15:03 UTC
Labels: bug, needs confirmation
