### ISSUE TITLE
Synology icon is not displayed in tray

### ISSUE THREAD

**Issue by legendofa** [polybar/polybar#2236] opened 2020-11-03 21:09 UTC
Every other icon is displayed in the bar except the synology-drive icon: https://aur.archlinux.org/packages/synology-drive/

Expected behavior: All icons are lined up in the tray.

Actual behavior: Synology icon is displayed at the top left of the screen.

Was not working before.

Did you also experience this bug in an earlier version of polybar?
Yes

## To Reproduce
A minimal but complete config with which the problem
occurs:
```
[colors]
background = ${xrdb:color0:#222}
foreground = #dfdfdf

[bar/example]
override-redirect = true
wm-restack = i3
width = 100%
height = 27
radius = 0.0
fixed-center = true

dpi-x = 120
dpi-y = 120

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

border-size = 0
border-color = #00000000

padding-left = 4
padding-right = 4

module-margin-left = 2
module-margin-right = 0

font-0 = vera:pixelsize=9;1
font-1 = uni
font-2 = icons
font-3 = symbola

modules-center = date

tray-position = right
tray-padding = 0
;tray-background = #aa00
tray-background = ${colors.background}
tray-maxsize = 20

cursor-click = pointer
cursor-scroll = ns-resize

bottom = true

[module/date]
type = internal/date
interval = 0.5

time = %H:%M:%S | %d. %m. %Y
time-alt = %H:%M:%S | %m. %d. %Y

format-prefix-foreground = ${colors.foreground-alt}
format-underline = #0a6cf5

label = %date% %time%l
```

*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
notice: Parsing config file: /home/julian/.config/polybar/config
notice: Loaded font "vera:pixelsize=9" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
notice: Loaded font "uni" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
notice: Loaded font "icons" (name=Icons, offset=0, file=/usr/share/fonts/TTF/icons.ttf)
notice: Loaded font "symbola" (name=Symbola, offset=0, file=/usr/share/fonts/TTF/Symbola.ttf)
```

## Screenshots

Top left:

![2020-11-03-220114_1920x1080_scrot](https://user-images.githubusercontent.com/34162874/98040470-3d371300-1e18-11eb-9c3c-51a824522260.png)

Bottom right:

![2020-11-03-220153_1920x1080_scrot](https://user-images.githubusercontent.com/34162874/98040476-40320380-1e18-11eb-8ada-0415cf514c86.png)

## Environment:
* WM: i3-gaps
* Distro: Arch Linux x86_64
* Output of `polybar -vvv`:

polybar 3.4.0-113-ga625e2b7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

**Comment by patrick96** [comment] 2020-11-03 22:40
Duplicate of #1679

**Closed by patrick96** 2020-11-03 22:40 UTC
