### ISSUE TITLE
 Missing required python module: xcbgen

### ISSUE THREAD

**Issue by 1m-N00b** [polybar/polybar#1972] opened 2019-12-27 15:22 UTC
## Build Process
`yay -Syu`
aur/polybar  3.4.1-1 -> 3.4.1-3

## Build Log
[Build Log](https://pastebin.com/TgCGP2F6)
[CMakeOutput.log](https://pastebin.com/t7ZuJ1BZ)
[CMakeError.log](https://pastebin.com/8Vjm1Dpt)

## Environment:
* Distro (with Version):Arch Linux x86_64(5.4.6-arch3-1)

**Comment by patrick96** [comment] 2019-12-27 15:32
Duplicate of #1882

**Closed by patrick96** 2019-12-27 15:32 UTC

**Comment by patrick96** [comment] 2019-12-27 15:33
You need to make sure you use system python when building, not pyenv. See the [wiki](https://github.com/polybar/polybar/wiki/Compiling#compiling).

Basically run `pyenv local system` before building or [build in a clean chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot)
