### ISSUE TITLE
Can't use "}" in cmd line

### ISSUE THREAD

**Issue by fxchmax** [polybar/polybar#2498] opened 2021-09-11 09:53 UTC
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [ ] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [ ] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

When I put "}" in a CMD line,polybar return this in the logs:
polybar|warn:  Invalid color in formatting tag detected: "fi", using fallback "#ffff0000". This is an issue with one of your formatting tags. If it is not, please report this as a bug.
polybar|error: Failed to parse contents (reason: Unrecognized attribute 's')

"{" just fine.

**Expected behavior:**

**Actual behavior:**

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
* If no, what was the last version where this worked correctly?

## To Reproduce

```dosini

```

## Polybar Log

```

```

## Environment:
* WM:bspwm
* Distro:Linux SAL 5.14.2-arch1-2 #1 SMP PREEMPT Thu, 09 Sep 2021 09:42:35 +0000 x86_64 GNU/Linux
* Output of `polybar -vvv`:
polybar 3.5.6

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

```

**Comment by patrick96** [comment] 2021-09-11 10:03
Duplicate of #2040

Will be fixed in 3.6.0

**Closed by patrick96** 2021-09-11 10:03 UTC
