### ISSUE TITLE
[Bug]: Icons partially cut off

### ISSUE THREAD

**Issue by rainer2208** [polybar/polybar#2911] opened 2023-02-05 20:55 UTC
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

I am using Polybar on an Asus Vivobook Laptop, my wm is i3 and my platform is Arch.

I have installed the wm and polybar a couple month ago, and right from the beginning some of the icons appear cut off, showing practically only 50% of it. In the screenshot, the tiem icon is visibly cut  in half ... whereas the sound icon is unaffected. 

It seems the icon are affected randomly... 

Any idea how to solve this? 

![Polybar](https://user-images.githubusercontent.com/23400899/216844655-adc9bc78-5fde-4b49-9ff5-a30ce69cb9b4.png)

### Minimal config

```dosini
[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/mybar]
width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = monospace;2

modules-left = xworkspaces xwindow  
modules-center = pulseaudio pacman-updates
modules-right = filesystem  xkeyboard memory cpu wlan eth date


cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = right

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true


[module/pacman-updates]
type = custom/script
format-prefix = "UPDATES "
format-prefix-foreground = ${colors.primary}
exec = checkupdates | wc -l
label = %output%
label-background = ${colors.alert}
label-padding = 4
;label = updates %output%
; "content" has the same properties as "format-NAME"
content-background = #000
content-foreground = #fff
content-padding = 4

;type = custom/script
;exex = checkupdates | wc -l
;interval = 1000
;label-active = updates %output%
;format.foreground = ${colors.foreground}
;format.foreground = #453456
;
;format-prefix = "try"
;format-prefix-foreground = #ff0000

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1


[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true
```

### Expected behavior

Icon appear with their complete shape 

### Actual behavior

Icons are partially cut off

### Window Manager and Version

i3

### Linux Distribution

Arch with latest updates

### Polybar version

```text
polybar 3.6.3
```

### Additional Context / Screenshots

![Polybar](https://user-images.githubusercontent.com/23400899/216844958-8ebcf419-2c54-4da9-bf3a-a54ee3afc76b.png)

**Comment by patrick96** [comment] 2023-02-05 21:28
This very much looks like a duplicate of #991.

Also, the config you posted is not the one used in the screenshot.

**Closed by patrick96** 2023-02-05 21:28 UTC
Labels: bug, needs confirmation

**Comment by rainer2208** [comment] 2023-02-06 19:09
hi, it was indeed a problem with the nerd font ... changing it to Mono solved the problem
