### ISSUE TITLE
[Bug]: Tray showing in fullscreen

### ISSUE THREAD

**Issue by marcothms** [polybar/polybar#2921] opened 2023-02-17 08:05 UTC
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Checkout polybar at 8cc1b4fc (at my time the newest)
2. Make
3. Run with adaptive tray

### Minimal config

```dosini
[colors]
bg = #2f383e
alt = #56635f
fg = #d3c6aa
accent = #93b259
inactive = #dfa000
alert = #e67e80

[bar/main]
modules-left = i3 title
modules-right = tray

[module/title]
type = internal/xwindow
label-maxlen = 60
label-foreground = ${colors.alt}

[module/i3]
type = internal/i3
pin-workspaces = true
enable-click = true
enable-scroll = true
show-all = true

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = 10;10

ws-icon-default = 

format = <label-state>
format-background = ${colors.bg}

label-focused = %icon%
label-focused-padding = 1
label-focused-foreground = ${colors.accent}

label-unfocused = %icon%
label-unfocused-padding = 1
label-unfocused-foreground = ${colors.alt}

label-visible = %icon%
label-visible-padding = 1

label-urgent = %icon%
label-urgent-padding = 1
label-urgent-foreground = ${colors.alert}

[module/tray]
type = internal/tray
```

### Polybar log

```text
notice: Parsing config file: /home/marc/.config/polybar/config.ini
notice: Listening for IPC messages (PID: 73628)
notice: Loading module 'i3' of type 'internal/i3'
notice: Loading module 'title' of type 'internal/xwindow'
notice: Loading module 'tray' of type 'internal/tray'
notice: Loaded 3 modules
```

### Expected behavior

I want to show my i3 workspaces and current open window (xwindow) to show on the left side. On the right side i want to show the tray (and other things, which I excluded for the minimal example, because it's also broken without them).
I want the tray to show to the left of the other modules, that's why I used the experimental feature to achieve this.

### Actual behavior

When having a window on fullscreen, switching to another workspace and then back to the initial workspace, the tray renders on top of the window (see screenshot). This does only happen, when there is a `modules-left` defined. Without `modules-left` it works correctly. Maybe it also has something to do, that the `modules-left` have a different fore- and background color, but every time I tested this it sometimes worked and sometime it didn't. The only certain thing is, that it works perfectly without left-side modules.

### Window Manager and Version

i3 version 4.22 (2023-01-02)

### Linux Distribution

Linux 6.1.11-200.fc37.x86_64 Fedora 37

### Polybar version

```text
Checked out commit 8cc1b4fc

polybar 3.6.3-89-g8cc1b4fc

Features: -alsa -curl +i3 -mpd -network(wireless-tools) -pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb -xrm -xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
Linker flags:  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
```

### Additional Context / Screenshots

Normal Bar:
![image](https://user-images.githubusercontent.com/39596050/219585580-5a4df8bb-762c-4ac6-b523-edd2d56d7534.png)

Fullscreening YT, switching workspaces back and fourth:
![image](https://user-images.githubusercontent.com/39596050/219585682-525024b4-d7fd-43a9-ac9f-a66dfa125bf8.png)

I'm well aware, that this feature is experimental and that #2689 exists. But I couldnt find a bug report to this, so maybe this can also be fixed for 3.7 release.

**Comment by patrick96** [comment] 2023-03-25 16:41
Duplicate of #425

The adaptive tray doesn't render the tray any differently, it still has the same issues as the old placement style.

**Closed by patrick96** 2023-03-25 16:41 UTC
Labels: bug, needs confirmation
