### ISSUE TITLE
[Bug]: Network module reporting wrong data

### ISSUE THREAD

**Issue by medwatt** [polybar/polybar#2691] opened 2022-04-19 14:45 UTC
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Run polybar the usual way with the network module enabled.

### Minimal config

```dosini
[module/network]
type = internal/network
interface = wlp4s0

interval = 1.0

format-connected = <label-connected>
format-connected-prefix = "󰤨 "
format-connected-prefix-foreground = ${colors.grey}

format-disconnected = <label-disconnected>
format-disconnected-prefix = "󰤭 "
format-disconnected-prefix-foreground = ${colors.red}

label-connected = %signal%%  %{F#808080}󰘡 %{F#EAEADD}%downspeed:8:10% %{F#808080}󰘣 %{F#EAEADD}%upspeed:8:10%%{F-}
label-disconnected = "disconnected"
```

### Expected behavior

The network module is not reporting the correct signal strewth of my WiFi connection.

### Actual behavior

Here's a video showing a comparison between the output of Polybar's network module and i3status-rust: https://streamable.com/0iubor. i3status-rust is reporting the correct data that corresponds to the output of `nmcli device wifi`.

### Window Manager and Version

i3 version 4.20.1

### Linux Distribution

Manjaro 21.2.6.1

### Polybar version

```text
polybar 3.6.2-34-g4961a7dc
```

**Comment by patrick96** [comment] 2022-04-22 15:29
I don't think polybar reports wrong info. The signal percentage is calculated from the signal strength in (dBm). Different tools use different formulas to derive a percentage from the dBm value and thus may produce different percentage values.
See [here](https://github.com/polybar/polybar/issues/2179#issuecomment-1106626482) for more info.

I'll mark this as a duplicate of #2179.

**Closed** 2022-04-23 09:37 UTC
Labels: duplicate
