### ISSUE TITLE
[Bug]: Tray stays on top of fullscreen apps

### ISSUE THREAD

**Issue by moson-mo** [polybar/polybar#2746] opened 2022-06-18 20:59 UTC
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Run polybar with the below config

### Minimal config

```dosini
[bar/right]
enable-ipc = true
width = 100%
height = 30

modules-right = tray date

[module/tray]
type = internal/tray
format = <tray>

[module/date]
type = internal/date
interval = 1
time = %H:%M:%S
label = %time%
```

### Polybar log

```text
otice: Parsing config file: config_test.ini
- config_parser: Parsing config_test.ini
* Created legacy ipc fifo at '/tmp/polybar_mqueue.60857'
* Opening ipc socket at '/run/user/1000/polybar/ipc.60857.sock'
notice: Listening for IPC messages (PID: 60857)
* Loaded monitor eDP (1920x1080+0+0)
* Configured DPI = 96x96
* Bar geometry: 1920x30+0+0; Borders: 0,0,0,0
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Setup user-defined modules
notice: Loading module 'tray' of type 'internal/tray'
notice: Loading module 'date' of type 'internal/date'
notice: Loaded 2 modules
* Starting application
- controller: Main thread id = 1
* Starting module/tray
* Starting module/date
* Entering event loop (thread-id=1)
- bar: Create renderer
- renderer: Get TrueColor visual
- renderer: Allocate colormap
- renderer: Allocate output window
- module/date: Thread id = 2
- renderer: Allocate window pixmaps
- renderer: Allocate graphic contexts
- renderer: Allocate alignment blocks
- renderer: Allocate cairo components
- renderer: Load fonts
warn: No fonts specified, using fallback font "fixed"
notice: Loaded font "fixed" (name=Noto Sans, offset=0, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
* Bar window: 0x1c00001
- bar: Reconfigure window
- bar: Set window WM_NAME
- bar: Set window _NET_WM_WINDOW_TYPE
- bar: Set window _NET_WM_STATE
- bar: Set window _NET_WM_DESKTOP
- bar: Set window _NET_WM_PID
- bar: Map window
- bar: Draw empty bar
- bar: Setup tray manager
- tray: Find systray selection atom for the default screen
* Activating tray manager
- tray: Create tray window
* Tray window: 0x1c00006
- tray: Restacking tray window
- bar: Set window WM_NAME / WM_CLASS
- tray: Set window WM_PROTOCOLS
- tray: Set window _NET_WM_WINDOW_TYPE
- tray: Set window _NET_WM_STATE
- tray: Set window _NET_WM_PID
- tray: Set window _NET_SYSTEM_TRAY_VISUAL
- tray: Set window _NET_SYSTEM_TRAY_ORIENTATION
- tray: Set _NET_SYSTEM_TRAY_COLORS to ffffffff
- tray: Change selection owner to 0x1c00006
- tray: visibility_change (state=0, activated=1, mapped=0, hidden=0)
* module/tray: Rebuilding cache
* module/date: Rebuilding cache
- bar: Force update
* Redrawing bar window
- tray: Reconfigure window (mapped=0, clients=0)
- tray: visibility_change (state=1, activated=1, mapped=0, hidden=1)
- renderer: flush(3 geom=62x30+1858+0, falloff=0)
- tray: visibility_change (state=1, activated=1, mapped=0, hidden=0)
- tray: visibility_change (state=1, activated=1, mapped=0, hidden=0)
- bar: Received expose event
* Notifying pending tray clients
- tray: Received client_message
* Processing docking request from 'Bluetooth Active
<b>1 Active Connection</b>' (0x2001ca4)
- tray: xembed = true
- tray: version = 0x1, flags = 0x1, XEMBED_MAPPED = true
- tray: Update client window
- tray: Configure client size
- tray: Add client window to the save set
- tray: Reparent client
- tray: Send embbeded notification to client
- tray: Map client
- tray: Received client_message
* Processing docking request from 'xfce4-power-manager' (0x1401e31)
- tray: xembed = true
- tray: version = 0x1, flags = 0x1, XEMBED_MAPPED = true
- tray: Update client window
- tray: Configure client size
- tray: Add client window to the save set
- tray: Reparent client
- tray: Send embbeded notification to client
- tray: Map client
- tray: Received client_message
* Processing docking request from 'Wi-Fi network connection “Auto dd-wrt” active: dd-wrt (58%)
VPN connection active' (0x1001ccb)
- tray: xembed = true
- tray: version = 0x1, flags = 0x1, XEMBED_MAPPED = true
- tray: Update client window
- tray: Configure client size
- tray: Add client window to the save set
- tray: Reparent client
- tray: Send embbeded notification to client
- tray: Map client
- tray: Received client_message
* Processing docking request from 'flameshot' (0x2600072)
- tray: xembed = true
- tray: version = 0x0, flags = 0x1, XEMBED_MAPPED = true
- tray: Update client window
- tray: Configure client size
- tray: Add client window to the save set
- tray: Reparent client
- tray: Send embbeded notification to client
- tray: Map client
- tray: Received map_notify
- tray: Set client mapped
- tray: Reconfigure clients
- tray: Reconfigure window (mapped=0, clients=4)
- tray: Reconfigure window / map
- tray: New window values, width=30, x=1858
- tray: Received map_notify
- tray: Set client mapped
- tray: Reconfigure clients
- tray: Reconfigure window (mapped=0, clients=4)
- tray: Reconfigure window / map
- tray: New window values, width=53, x=1858
- tray: Received map_notify
- tray: Set client mapped
- tray: Reconfigure clients
- tray: Reconfigure window (mapped=0, clients=4)
- tray: Reconfigure window / map
- tray: New window values, width=76, x=1858
- tray: Received map_notify
- tray: Set client mapped
- tray: Reconfigure clients
- tray: Reconfigure window (mapped=0, clients=4)
- tray: Reconfigure window / map
- tray: New window values, width=99, x=1858
- tray: Received map_notify
- tray: Update container mapped flag
* Redraw tray container (id=0x1c00006)
- tray: Refreshing window
* Redraw tray container (id=0x1c00006)
- tray: Refreshing window
* Redraw tray container (id=0x1c00006)
- tray: Refreshing window
* Redraw tray container (id=0x1c00006)
- tray: Refreshing window
* Redraw tray container (id=0x1c00006)
- tray: Refreshing window
* Redraw tray container (id=0x1c00006)
- tray: Refreshing window
* module/tray: Rebuilding cache
- bar: Force update
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
- tray: visibility_change (state=0, activated=1, mapped=1, hidden=0)
- tray: Received unmap_notify
- tray: Update container mapped flag
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=0, clients=4)
- tray: New window values, width=99, x=1759
- tray: visibility_change (state=1, activated=1, mapped=0, hidden=1)
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
- tray: Received map_notify
- tray: Update container mapped flag
* Redraw tray container (id=0x1c00006)
- tray: Refreshing window
* Redraw tray container (id=0x1c00006)
- tray: Refreshing window
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
- tray: visibility_change (state=1, activated=1, mapped=1, hidden=0)
* Redraw tray container (id=0x1c00006)
- tray: Refreshing window
- tray: visibility_change (state=1, activated=1, mapped=1, hidden=0)
* Redraw tray container (id=0x1c00006)
- tray: Refreshing window
- bar: Received expose event
* Redraw tray container (id=0x1c00006)
- tray: Refreshing window
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
* module/date: Rebuilding cache
* Redrawing bar window
- tray: Reconfigure window (mapped=1, clients=4)
- tray: New window values, width=99, x=1759
- renderer: flush(3 geom=161x30+1759+0, falloff=0)
notice: Received signal(2): Interrupt
* Eventloop finished
notice: Termination signal received, shutting down...
- controller: Detach signal receiver
- controller: Stop modules
* module/tray: Stopping
- module/tray: Release sleep lock
* Deconstruction of module/tray took 0 ms.
* module/date: Stopping
- module/date: Release sleep lock
* Deconstruction of module/date took 0 ms.
- module/tray: Deconstructing
- module/date: Deconstructing
* Deactivating tray manager
- tray: Unset selection owner
- tray: Unembed clients
- tray: Destroy window
- ipc: Removing named pipe at: /tmp/polybar_mqueue.60857
* Waiting for spawned processes to end
* Reached end of application...
```

### Expected behavior

Tray should not be visible on a full-screen window.

### Actual behavior

Tray stays visible on top of a full screen window. F.e.: Run `mpv` with a video in full screen mode.

### Window Manager and Version

i3-gaps 4.20.1

### Linux Distribution

Arch Linux

### Polybar version

```text
polybar 3.5.7-337-gb7e321bb

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

**Comment by raffael0** [comment] 2022-06-18 21:27
I think this is a duplicate of #425

**Closed** 2022-06-18 22:27 UTC
Labels: bug, needs confirmation

**Comment by moson-mo** [comment] 2022-06-18 22:53
> I think this is a duplicate of #425

Not sure. This issue occurred after https://github.com/polybar/polybar/commit/b2c5d8e0e228031844f28ecd91fb841f11842fb2

**Comment by patrick96** [comment] 2022-07-09 09:36
The underlying issue is still the same as #425
