### ISSUE TITLE
The urgent state for EWMH2 workspaces get reset when switching to any non-urgent workspace

### ISSUE THREAD

**Issue by Hund** [polybar/polybar#2453] opened 2021-06-20 10:27 UTC
The urgent state for EWMH2 workspaces get reset when switching to any non-urgent workspace.

* WM: Herbstluftwm
* Distro: Gentoo
* Output of `polybar -vvv`:

```
polybar 3.5.5

Features: +alsa -curl +i3 -mpd -network(wireless-tools) -pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Gentoo
Compiler: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -march=sandybridge -O2 -pipe -Wall -Wextra -Wpedantic 
Linker flags: -Wl,-O1 -Wl,--as-needed 
```

**Comment by patrick96** [comment] 2021-06-21 18:21
Duplicate of #1081 

This is fixed in the next release.

**Closed by patrick96** 2021-06-21 18:21 UTC

**Comment by Hund** [comment] 2021-06-21 19:24
My apologies. I totally forgot to search for it. :|
