### ISSUE TITLE
Cannot click or scroll pulseaudio modules other than the first if more than one are present on the bar

### ISSUE THREAD

**Issue by roobre** [polybar/polybar#2221] opened 2020-10-19 13:36 UTC
## Describe the issue

If more than one `pulseaudio` modules are present on the bar (targeting different sinks) the first one will "eat" all inputs done to the second, including clicks and scroll wheel.

The second module still responds and updates when I change volume and status through other means (e.g. pavucontrol).

**Expected behavior:**

Both modules should operate independently and handle their own inputs.

**Actual behavior:**

Scrolling or clicking the second module changes volume and mutes the first module rather than the one being hovered. The first module works normally.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
  - N/A
* If no, what was the last version where this worked correctly?
  - N/A

## To Reproduce
*A minimal but complete config with which the problem occurs:*

```dosini
[module/volume-hp]
type = internal/pulseaudio
sink = alsa_output.usb-SABAJ_SABAJ_DA3_v1.2-00.iec958-stereo

use-ui-max = false

format-volume =  <label-volume>
format-volume-underline = ${colors.cBlue}

label-volume = %percentage%%

label-muted = -
format-muted =  <label-muted>
format-muted-underline = ${colors.cRed}


[module/volume-sp]
type = internal/pulseaudio
sink = alsa_output.pci-0000_00_1f.3.analog-stereo

use-ui-max = false

format-volume = <ramp-volume> <label-volume>
format-volume-underline = ${colors.cBlue}

label-volume = %percentage%%
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

format-muted = <label-muted>
format-muted-underline = ${colors.cRed}
label-muted = 
```

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
warn: module/i3: Attempting to reconnect socket (reason: Unexpected EOF while reading header)
warn: module/i3: Attempting to reconnect socket (reason: Unexpected EOF while reading header)
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: i3
* Distro: Arch Linux
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=native -mtune=native -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context
-

**Comment by patrick96** [comment] 2020-10-19 15:23
Duplicate of #1172

See [Known-Issues](https://github.com/polybar/polybar/wiki/Known-Issues#with-multiple-modules-of-the-same-type-actions-on-those-modules-control-the-leftmost-module)

**Closed by patrick96** 2020-10-19 15:23 UTC

**Comment by roobre** [comment] 2020-10-19 18:05
Ouch, I searched for "pulseaudio" thinking it would be more specific. Sorry!
