### ISSUE TITLE
Module envs

### ISSUE THREAD

**Issue by pbakiewicz** [polybar/polybar#2375] opened 2021-02-13 17:55 UTC
## Why does polybar need this feature?
If we accept module inheritence it would let programmers use DRY principle. E.g. If I could write module like
```
[module/smth1]
type = custom/ipc
param = param1
hook-0 = cmd ${param}
hook-1 = cmd2 ${param}
hook-2 = cmd2 ${param}
```
Then if I'd like to create similar module I could only:
```
[module/smth2]
inherit = module/smth1
param = param2
```
Instead of overriding all my hooks.

**Comment by patrick96** [comment] 2021-02-14 20:27
Duplicate of #954

**Closed by patrick96** 2021-02-14 20:27 UTC
