### ISSUE TITLE
Click-right option for date module.

### ISSUE THREAD

**Issue by agoodfellow123** [polybar/polybar#2608] opened 2022-02-27 13:32 UTC
I like how I can summon a volume control program when I right click the volume module and I think it would be wonderful if we can right click the date module to run a calendar program such as calcurse.

I think everyone can use such feature to easily access their calendar.

As for the solution, I don't know the internals of polybar but at least in my head, you can probably port the pulseaudio modules "click-right" and "click-middle" options to the date module.

**Comment by patrick96** [comment] 2022-02-27 16:35
Yes!

There is a larger ongoing effort to bring all missing click, scroll and double-click settings to all modules: #1524 

As a temporary workaround, you can use [action tags](https://github.com/polybar/polybar/wiki/Formatting#action-a) to define your own clickable regions:

```dosini
format = %{A3:cmd:}<label>%{A3}
```

I'm closing this as a duplicate of #1524

**Closed by patrick96** 2022-02-27 16:35 UTC
Labels: feature, needs confirmation
