### ISSUE TITLE
xkeyboard: display only variant

### ISSUE THREAD

**Issue by julien-h** [polybar/polybar#1904] opened 2019-10-20 15:29 UTC
## Is your feature request related to a problem? Please describe.
I use the colemak keybaard. The full name displayed by `%name%` is long and takes up too much space on my polybar.

## Why does polybar need this feature?
As for most Colemak users, I want to switch easily between Colemak (for me) and US for others that use my PC. For this reason, the xkeyboard module is very useful. However, we only need to display the variant (i.e. the stuff between parens), not the full name. 

Also, just cutting a string to keep what's inside `(` and `)` should be quick to implement in the original `xkeyboard` module.

## Describe the solution you'd like
Implement a `%variant%` tag for xkeyboard that only displays the part of the `%name%` tag that is between `(` and `)`.

## Describe alternatives you've considered
Implementing my own `xkeyboard`-like module. This is not efficient however because (1) `xkeyboard` is in the C++ code and (2) communicating with `xkb` to automatically change the displayed layout name/variant is not trivial.

**Comment by patrick96** [comment] 2019-10-21 08:18
Hi, we had that request before. It's already on our TODO list.

Duplicate of #316

**Closed by patrick96** 2019-10-21 08:18 UTC
Labels: duplicate
