### ISSUE TITLE
ws-icon doesnt work for more than 9 workspaces

### ISSUE THREAD

**Issue by hugohabicht01** [polybar/polybar#2082] opened 2020-05-01 10:09 UTC
## Describe the issue
I have a pretty normal setup with i3 and polybar with 10 workspaces in i3. I now tried to assign icons to workspaces but for workspace 10 it shows the same icon as for workspace 1. I already tried putting the number in quotation marks but that didnt solve the issue.

**Expected behavior:**
I should see the icon I assigned for workspace 10 and not the one for ws 1.

**Actual behavior:**
It shows the one for ws 1
**Was it working before?**
Never tried it before
## To Reproduce
This is the configuration for the i3 module
```dosini
[module/i3]
type = internal/i3
;format = <label-state> <label-mode>

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = "10;10"


index-sort = true
fuzzy-match = true
wrapping-scroll = false

label-active-font = 7
; Only show workspaces on the same output as the bar
;pin-workspaces = true

label-mode-foreground = #000
label-mode-background = ${solarized.yellow}

; focused = Active workspace on focused monitor
;label-focused = %name%
;label-focused-background = ${module/bspwm.label-focused-background}
;label-focused-underline = ${module/bspwm.label-focused-underline}
;label-focused-padding = ${module/bspwm.label-focused-padding}

label-focused = %icon%
label-focused-background = ${solarized.base02}
label-focused-underline = ${solarized.yellow}
;label-focused-padding = ${module/bspwm.label-focused-padding}
label-focused-padding = 1
label-unfocused-padding = 1
; unfocused = Inactive workspace on any monitor
label-unfocused = %icon%

;label-unfocused-padding = ${module/bspwm.label-occupied-padding}
; visible = Active workspace on unfocused monitor
label-visible = %icon%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
N/A

## Screenshots
This is what it shows. The icon on the far right should be a headphones icon instead of the code icon.
![image](https://user-images.githubusercontent.com/39224742/80798273-51b5fc80-8ba4-11ea-8498-40d7459fc992.png)

## Environment:
* WM: i3
* Distro: I use arch btw
* Output of `polybar -vvv`:
```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context
I tried it with 2 monitors as well as with 1 doesn't make a difference

**Comment by patrick96** [comment] 2020-05-01 13:09
Duplicate of #2041 

This is fixed in the upcoming release. For now, disable fuzzy-match

**Closed by patrick96** 2020-05-01 13:09 UTC
