### ISSUE TITLE
Built-in Github Module authenticates via deprecated method (query-params)

### ISSUE THREAD

**Issue by ndom91** [polybar/polybar#2139] opened 2020-07-05 22:55 UTC
## Describe the issue
The built-in Github notification module uses a token passed via query params to authenticate. This method is deprecated and spawns a Github warning email with the following follow-up link:

https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param

Looks like Github won't be removing this feature entirely until May 5, 2021 though thankfully. Recommended fixes are included in the link above as well.

**Comment by patrick96** [comment] 2020-07-06 00:53
Duplicate of #2002 

This is already fixed

**Closed by patrick96** 2020-07-06 00:53 UTC

**Comment by ndom91** [comment] 2020-07-06 02:02
Ah I did a search and didn't find anything. Good to hear
