### ISSUE TITLE
Error doing "make -j$(nproc)"

### ISSUE THREAD

**Issue by smourog** [polybar/polybar#2314] opened 2020-12-18 01:33 UTC
[  1%] Generating ../../../lib/xpp/include/xpp/proto/x.hpp
[  2%] sphinx-build man: see doc/builder-man.log
[  2%] sphinx-build html: see doc/builder-html.log
[  6%] Built target jsoncpp_lib_static
[ 11%] Built target polybar-msg
[ 12%] Generating ../../../lib/xpp/include/xpp/proto/composite.hpp
Traceback (most recent call last):
  File "/opt/polybar/lib/xpp/generators/cpp_client.py", line 3101, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python3/dist-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python3/dist-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python3/dist-packages/xcbgen/xtypes.py", line 5, in <module>
    from xcbgen.align import Alignment, AlignmentLog
  File "/usr/lib/python3/dist-packages/xcbgen/align.py", line 5, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:93: ../lib/xpp/include/xpp/proto/x.hpp] Error 1
make[2]: *** Deleting file '../lib/xpp/include/xpp/proto/x.hpp'
[ 13%] Generating ../../../lib/xpp/include/xpp/proto/randr.hpp
Traceback (most recent call last):
  File "/opt/polybar/lib/xpp/generators/cpp_client.py", line 3101, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python3/dist-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python3/dist-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python3/dist-packages/xcbgen/xtypes.py", line 5, in <module>
    from xcbgen.align import Alignment, AlignmentLog
  File "/usr/lib/python3/dist-packages/xcbgen/align.py", line 5, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:81: ../lib/xpp/include/xpp/proto/composite.hpp] Error 1
make[2]: *** Deleting file '../lib/xpp/include/xpp/proto/composite.hpp'
[ 14%] Generating ../../../lib/xpp/include/xpp/proto/xkb.hpp
Traceback (most recent call last):
  File "/opt/polybar/lib/xpp/generators/cpp_client.py", line 3101, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python3/dist-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python3/dist-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python3/dist-packages/xcbgen/xtypes.py", line 5, in <module>
    from xcbgen.align import Alignment, AlignmentLog
  File "/usr/lib/python3/dist-packages/xcbgen/align.py", line 5, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:85: ../lib/xpp/include/xpp/proto/randr.hpp] Error 1
make[2]: *** Deleting file '../lib/xpp/include/xpp/proto/randr.hpp'
Traceback (most recent call last):
  File "/opt/polybar/lib/xpp/generators/cpp_client.py", line 3101, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python3/dist-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python3/dist-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python3/dist-packages/xcbgen/xtypes.py", line 5, in <module>
    from xcbgen.align import Alignment, AlignmentLog
  File "/usr/lib/python3/dist-packages/xcbgen/align.py", line 5, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:89: ../lib/xpp/include/xpp/proto/xkb.hpp] Error 1
make[2]: *** Deleting file '../lib/xpp/include/xpp/proto/xkb.hpp'
make[2]: Target 'lib/xpp/CMakeFiles/xpp.dir/depend' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:660: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
[ 17%] Built target i3ipc++
WARNING: html_static_path entry '/opt/polybar/doc/_static' does not exist
WARNING: html_static_path entry '/opt/polybar/doc/_static' does not exist
[ 17%] Built target doc_html
[ 17%] Built target doc_man
[ 17%] Built target doc
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:149: all] Error 2
make: Target 'default_target' not remade because of errors.

**Comment by patrick96** [comment] 2020-12-18 02:01
Duplicate of #2293

**Closed by patrick96** 2020-12-18 02:01 UTC
