### ISSUE TITLE
Tray icon transparency problem

### ISSUE THREAD

**Issue by xorph** [polybar/polybar#854] opened 2017-11-21 07:20 UTC
Hello everybody,

i have a problem with the polybar tray. The dropbox icon appears with transparent background und fragments of the time text. I have no clue what this causing this issue. Can anybody help? 

![screen](https://user-images.githubusercontent.com/8446421/33059270-dd820e5a-ce93-11e7-9721-0fcc8a3a71b5.png)

```
polybar 3.0.5-git

Features: +alsa +curl +i3 -mpd +network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm

Build type: RelWithDebInfo
Compiler: /usr/bin/clang++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

Arch Linux 
Kernel 4.13.12-1-ARCH
i3-gaps + `compton -f -b`
Intel Integrated Graphics

Best regards

**Comment by kronn** [comment] 2017-11-21 09:42
Just to add another data-point to this:
I have similar issues with text-fragments, but not transparency of the tray:

![polybar-tray-artifact](https://user-images.githubusercontent.com/72198/33064725-f2ea48a8-cea6-11e7-9502-c2ba42e97191.png)

The telegram-icon has a transparent background itself, though.

I would expect that the background is cleared before painting the tray and its icons.
I see however artifacts from the previous text-content in the bar.
This only happens sometimes. Removing Telegram from the tray and readding it (well, by restarting the app) fixes the problem.

```
$ polybar -vv
polybar 3.0.5

Features: +alsa +curl -i3 +mpd +network

X extensions: +randr (-monitors) -render -damage -sync -composite +xkb +xrm

Build type: RelWithDebInfo
Compiler: /usr/bin/g++
Compiler flags:  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: 
```
Ubuntu 16.04.3 LTS
Kernel  4.4.0-98-generic
xmonad 0.13 with `compton -b --backend glx --paint-on-overlay`
Intel Corporation Broadwell-U Integrated Graphics

**Comment by xorph** [comment] 2017-11-21 12:05
Good point. Dropbox has a transparent background also and it looks like i see artifacts of the previous background (which is slightly different in my case) and text.

**Comment by patrick96** [comment] 2017-11-26 19:10
Does this also happen, if compton (or any other compositioner) is not running?

**Comment by kronn** [comment] 2017-11-26 20:33
I killed compton and restarted polybar a couple of times. I cannot reproduce the problem. 

I will experiment in the coming days with compton-settings to narrow it down for my setup. Is there a good place in the documentation where results can go (aside from a comment on this issue here)?

**Comment by patrick96** [comment] 2017-11-26 20:48
If the problem doesn't occur without compton then it is most likely a transparency issue. Polybar isn't that good with transparency and the tray is even worse. Maybe try to set `tray-transparent = false` and/or set the tray background to a non transparent color.

**Comment by kronn** [comment] 2017-11-27 08:59
I have not configured the tray to be transparent (though I think @xorph has). The issue happens only on the tray-icon that is in itself transparent. Explicitely setting the tray to be non-transparent did not change the display problem.

**Comment by xorph** [comment] 2017-11-27 09:17
The bar itself is set transparent. But the tray background is set to a non transparent color and `tray-transparent` is set to `false`.

**Comment by kronn** [comment] 2017-11-27 18:35
I could not find a suitable compton-setting for this.

**Comment by patrick96** [comment] 2017-11-27 23:04
Yeah this is definitely a tray issue. Right now the only way to fix this seems to be to disable compton which is not ideal. The tray feature has quite a lot of problems now and needs some major reworks, I don't know when this is going to happen, since that is going to be a pretty large undertaking.

**Comment by kartongsaft** [comment] 2017-12-17 19:12
I can confirm the issue with Polybar 3.1.0.

![image](https://user-images.githubusercontent.com/18282546/34082851-7e2a9890-e366-11e7-9b58-3cd4f4b6c871.png)

**Comment by NBonaparte** [comment] 2017-12-17 23:34
Which apps in particular have tray artifacts? I have a suspicion that it's only Qt5 apps which have this issue, as Dropbox and Telegram both exhibit them. There are known issues with the tray: https://github.com/qbittorrent/qBittorrent/issues/3173
If this is the case, then unfortunately I don't think we can do anything about it unless we stop using XEMBED or it is fixed on their end.

**Comment by kartongsaft** [comment] 2018-01-11 17:06
Is there an alternative to XEMBED that is compatible that could be implemented instead?

**Comment by IvanMalison** [comment] 2018-02-27 03:46
> If this is the case, then unfortunately I don't think we can do anything about it unless we stop using XEMBED or it is fixed on their end.

Just to add another datapoint:
https://github.com/travitch/taffybar/issues/177

experiences this issue as well with a total unrelated implementation.

XEMBED has all kinds of issues in general anyway, so its probably simply best to try to move on to one of the newer systray implementations.

**Comment by fat-fighter** [comment] 2018-03-29 07:46
Not a solution but a bit of a hack. I am using dropbox and am facing the same problem, but if you launch compton after dropbox has started, i.e. the dropbox icon is up and running on polybar, then the issue does not appear. I use the following script on startup (I'm using i3) which launches everything nicely

```
killall -q polybar compton

while pgrep -x polybar >/dev/null; do
	sleep 1;
done

polybar --config=/home/fat-fighter/.config/polybar/config bot &

dropbox stop; dropbox start

sleep 5

while pgrep -x compton >/dev/null; do
	sleep 1;
done
compton --config ~/.config/compton/compton.conf &
```

I am not sure if a permanent solution exists at this time.

**Comment by kartongsaft** [comment] 2018-04-05 19:05
For the moment, I don't have any issues and I hope it stays that way; still a great tip!

![image](https://user-images.githubusercontent.com/18282546/38386096-fd5c0f38-3913-11e8-9b2b-d7bee302700a.png)

**Comment by patrick96** [comment] 2018-11-21 16:23
Does anyone still have this issue with the latest polybar commit (not 3.2.1)? We did some work on the tray transparency in #595.

**Comment by patrick96** [comment] 2018-12-03 08:53
Dang.

**Comment by devpew** [comment] 2018-12-07 18:22
I have the same problem

i3 version 4.16

polybar 3.2.1

Features: +alsa +curl +i3 -mpd +network +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

**Comment by EmilyBjoerk** [comment] 2019-01-26 11:01
I'm not sure if this is the same issue but I frequently see tray icons rendered with their transparent regions as black instead of transparent.

See for example the hangouts icon:
![image](https://user-images.githubusercontent.com/5306929/51786239-b7296b00-2161-11e9-9ed4-fc5d8b3c33aa.png)

But also happens with the gtk-redshift icon (left most).

This is on git master commit a7ad68d. 

    [ebuild   R   *] x11-misc/polybar-9999::gentoo  USE="alsa curl i3wm ipc mpd network pulseaudio" PYTHON_TARGETS="python2_7" 0 KiB

**Comment by mietzen** [comment] 2019-06-23 17:38
I can confirm this bug with the dark tray icon of KeepassXC

```
polybar --version
polybar 3.3.0-99-g0740382

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

i3 --version
i3 version 4.16.1-186-g78372ed2 (2019-06-22, branch "gaps-next") © 2009 Michael Stapelberg and contributors

uname -a
Linux 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

cat .config/compton/config 
backend = "glx";
shadow = false;

fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;

vsync = "opengl-swc";
detect-client-opacity = true;
inactive-opacity = 0.95;
opacity-rule = ["95:class_g = 'Gnome-terminal' && window_type = 'normal'",
                "95:class_g = 'Code'"];

```

![Screenshot from 2019-06-23 19-37-24](https://user-images.githubusercontent.com/31704359/59979910-79d0e880-95ee-11e9-9818-1d14cdf9e2b0.png)

**Comment by mvrozanti** [comment] 2020-01-04 21:14
Mine just went full transparency
![image](https://user-images.githubusercontent.com/11381662/71771678-f8073380-2f1d-11ea-9613-a19a714d6c80.png)

**Comment by patrick96** [comment] 2023-03-25 21:13
We have recently implemented a new tray that runs as a module where we rewrote a lot of the rendering code (#2609, #2689).

Some of these rendering issues may be fixed by this, but there are still some that may occur (I have been struggling to fix the dropbox icon using arbitrary images as its background data).
I am going to close this issue, if you experience rendering issues like these while using the new tray module (the old tray using `tray-position` still has the same issues), please report the application and your polybar version (`polybar -v`) together with a screenshot in #2933.

**Closed by patrick96** 2023-03-25 21:13 UTC
Labels: tray
