### ISSUE TITLE
Ability to have Tooltips when hovering over a label

### ISSUE THREAD

**Issue by tobeypeters** [polybar/polybar#2350] opened 2021-01-09 03:44 UTC
Just as the title says, we need the ability to get tooltips when we hover over a label.

Just need at the minimal, two properties:

HoverLabel <--- What to display
HoverTimer <--- How long to display.  Default could be as long as the mouse is over the label

Formatting can be inherited from the label. You don't have to be nice and give the ability to override formatting.

**Comment by patrick96** [comment] 2021-01-09 07:30
Duplicate of #534

**Closed by patrick96** 2021-01-09 07:30 UTC
