### ISSUE TITLE
Click events on some modules

### ISSUE THREAD

**Issue by eoli3n** [polybar/polybar#273] opened 2016-12-26 23:11 UTC
I was thinking that every modules were clickable. It seems not.

Is there a way to add vars to be able to scroll and click for some modules ?

```
[module/backlight]
scroll-up = light -A 5
scroll-down = light -U 5

[module/volume]
scroll-up = amixer set Master 5%+
scroll-down = amixer set Master 5%-

[module/wlan]
click-left = connman-gtk
```

**Comment by jaagr** [comment] 2016-12-27 00:58
Yeah this will be added. For backlight you can use the `internal/xbacklight` module instead (if your driver supports it) that implements scroll handlers to adjust the value. And the volume one is already supported using `internal/volume`

**Comment by eoli3n** [comment] 2016-12-27 12:11
ah, it works with volume, didn't see it :)
xbacklight dont work for me, that's why i use "light" instead of xbacklight tool.
cool if this will be added.
Great work BTW, i come from conky cli bar, it's just amazingly cool and easy to understand/configure, thx a lot

**Comment by eoli3n** [comment] 2017-01-03 06:03
For now, i use
```
label-connected = "%{A1:connman-gtk:} %essid%%{A}"
```

**Comment by Tadly** [comment] 2017-04-07 11:47
huge +1 for the ability to overwrite all click/scroll events on a per module level.

e.g. I'd rather have `pavucontrol` open when left clicking on volume and mute by mid-clicking.
I do have quite a lot of applications that'd require overwriting default click behavior (no reason to list all of them, that one should suffice :) )

**Comment by jaagr** [comment] 2017-04-07 13:24
@Tadly until it's been implemented I'd recommend using a custom script module since it can be configured however you want.

**Comment by Tadly** [comment] 2017-04-07 14:35
@jaagr will do (or try at least), just wanted to highlight the need for said feature and as neither the initial issue nor *a* comment specified details one could upvote (nice for github to finally have such a feature) I just went ahead and commented it :)

**Comment by munyari** [comment] 2017-05-12 04:39
Note sure if this is the right issue, but would it be possible to define a module that changes appearance when you click it, like the date module? e.g. if the bar had icons only and clicking on an icon reveals some related text.

**Comment by jaagr** [comment] 2017-05-12 06:59
@munyari sure, using the ipc module. [See the example on the wiki](https://github.com/jaagr/polybar/wiki/Module:-ipc#examples)

**Comment by munyari** [comment] 2017-05-12 15:07
eek, thank you @jaagr!

**Comment by miguelpduarte** [comment] 2018-05-14 22:31
Is this planned to be worked on in the near future? I would find it interesting to be able to show a popup listing the estimated current battery life time when left clicking the battery module, for example.

**Comment by patrick96** [comment] 2018-05-15 12:36
Near future: No? Most of the functionality that this would bring can already be emulated by wrapping the module format or label key with `%{A1:your-cmd:}...%{A}` or any other action tag (See [Wiki](https://github.com/jaagr/polybar/wiki/Formatting#action-a)).

But this is something that I want to have be part of all modules by default because currently it's a bit messy with every module implementing the click-handlers itself, but as I said it's not our top priority right now because it's not a bug and there is a workaround. We're more focused on fixing bugs and other issues at the moment.

**Comment by ksunden** [comment] 2019-02-13 01:54
Would be nice if the `internal/github` module had click actions something like "left click > $BROWSER https://github.com/notifications" and "right click > recheck number of notifications"

**Comment by rieje** [comment] 2019-03-13 23:23
@patrick96 For your workaround, it's not possible to replicate *-alt (e.g. `date` vs. `date-alt` in the `date module`), right?

For example, I want to have the battery module show the battery percentage, and left click toggle to  expand that to show the remaining time left (`%time%`).

**Comment by patrick96** [comment] 2019-04-06 14:54
@rieje No this is not possible for the battery module. There has been a proposal to implement similar functionality in more modules but it added a *lot* of bloat to our code so we didn't merge it.

**Comment by thepenguinthatwants** [comment] 2021-01-28 19:53
Is it still not supported to have a left click to open gsimplecal when clicking on date? Tried quite a while but not sure how to get it.

**Comment by patrick96** [comment] 2021-01-28 21:56
@thepenguinthatwants You can use action tags: https://github.com/polybar/polybar/issues/273#issuecomment-389150884

**Comment by patrick96** [comment] 2022-10-17 18:58
Closing in favor of #1524

**Closed by patrick96** 2022-10-17 18:58 UTC
Labels: feature
