### ISSUE TITLE
Failed to put tray above 0x1200001

### ISSUE THREAD

**Issue by StarrKiss** [polybar/polybar#1802] opened 2019-06-05 14:35 UTC
Getting this error:
Failed to put tray above 0x1200001

and the tray does not appear anywhere on polybar. This is after removing wm and stacking. it doesnt even return to how to was before. The tray simply does not appear.

**Comment by patrick96** [comment] 2019-06-05 15:17
Duplicate of #425

**Closed by patrick96** 2019-06-05 15:17 UTC
