### ISSUE TITLE
Scrolling capability for hidden modules by System Tray

### ISSUE THREAD

**Issue by mepowerleo10** [polybar/polybar#1898] opened 2019-10-15 11:04 UTC
It'd be a nice feature if hidden modules could be scrolled to reveal the hidden content. i.e. the **systemtray** might expand to hide some modules, notice how the date module fades, if the another application is added to the **systemtray** the date module will not be visible. But if it could be scrolled, that would be convenient.

![Screenshot from 2019-10-15 13-52-22](https://user-images.githubusercontent.com/26873863/66826250-bab18c00-ef54-11e9-9591-b7ebb1ddec53.png)

**Comment by patrick96** [comment] 2019-10-15 13:46
This looks like a duplicate of #591 

It's not actually intentional that the tray overlaps some of the modules, it's a bug that we haven't been able to fix for a long time.

I would suggest adding something like `label-margin-right = 3` to the date module to force a bit of separation between the date module and the tray.

**Closed by patrick96** 2019-10-15 13:46 UTC
